import { useEffect,useState } from 'react';
import { projectStageLabel,type ProjectState } from '../../domain/project-state/projectState';
import { businessStages,derivePortfolio } from '../../domain/project-state/portfolio';
import { loadPortfolio } from '../../infrastructure/project-state/portfolioRepository';

export function PipelineSummary({items}:{items:ProjectState[]}){
  const active=items.filter(p=>p.status==='active'&&businessStages.includes(p.stage));
  const distribution=businessStages.map((stage,index)=>({stage,index,count:active.filter(p=>p.stage===stage).length}));
  return <section className="portfolio-card pipeline-summary"><div className="card-heading"><h2>Pipeline summary</h2><span>{active.length} active pursuits</span></div><div className="pipeline-split" role="img" aria-label={distribution.map(d=>`${projectStageLabel(d.stage as ProjectState['stage'])}: ${d.count}`).join(', ')}>{distribution.filter(d=>d.count).map(d=><span key={d.stage} className={`split-color-${d.index}`} style={{width:`${d.count/active.length*100}%`}} />)}</div><div className="pipeline-legend">{distribution.map(d=><div key={d.stage}><i className={`split-color-${d.index}`} aria-hidden="true"/><span>{d.stage==='predevelopment'?'Predev':projectStageLabel(d.stage as ProjectState['stage'])}</span><strong>{active.length?Math.round(d.count/active.length*100):0}% <small>({d.count})</small></strong></div>)}</div>{!active.length?<p>No active pursuits recorded.</p>:null}<p className="summary-placeholder"><strong>AI summary · Coming later</strong><span>A narrative summary of pipeline changes and priorities will appear here once connected.</span></p></section>;
}
export function PortfolioWorkspace({onOpen}:{onOpen:(id:string,business:boolean)=>void}){
  const [data,setData]=useState<Awaited<ReturnType<typeof loadPortfolio>>>(),[error,setError]=useState<string>(),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);setError(undefined);loadPortfolio().then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Portfolio could not load.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[refresh]);
  if(loading)return <p role="status">Loading portfolio…</p>;
  if(error)return <section className="portfolio-card"><p role="alert">{error}</p><button onClick={()=>setRefresh(v=>v+1)}>Try again</button></section>;
  if(!data)return null;
  const today=new Date().toLocaleDateString('en-CA');
  const summary=derivePortfolio(data.projects,data.actions,data.risks,today);
  const projectName=(id:string)=>data.projects.find(p=>p.id===id)?.name??'Project';
  return <div className="portfolio-home"><div className="home-welcome"><div><h2>Your portfolio, at a glance.</h2><p>Current work, priorities and the next decisions.</p></div><button className="secondary" onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div>
    <div className="portfolio-metrics">{[['Active pursuits',summary.pipeline.length],['Authorized projects',summary.authorized.length],['Overdue actions',summary.overdue.length],['Open risks / issues',summary.openRisks.length]].map(([label,value])=><article className="portfolio-card metric-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
    <div className="portfolio-columns"><div><section className="portfolio-card"><div className="card-heading"><h2>Operational attention</h2><span>Active records</span></div><div className="attention-metrics"><p><strong>{summary.blocked.length}</strong> blocked actions</p><p><strong>{summary.materialRisks.length}</strong> high / critical / material risks</p><p><strong>{summary.held.length}</strong> pursuits on hold</p></div><p className="metric-note">Based on recorded actions and risks. Zero recorded issues does not certify project health.</p></section><section className="portfolio-card"><div className="card-heading"><h2>Upcoming deadlines</h2><span>Next 7 days</span></div>{summary.upcoming.length?summary.upcoming.slice(0,8).map(a=><button className="deadline-row" key={a.id} onClick={()=>onOpen(a.project_state_id,businessStages.includes(data.projects.find(p=>p.id===a.project_state_id)!.stage))}><time>{a.due_date}</time><span><strong>{a.title}</strong><small>{projectName(a.project_state_id)}</small></span><span aria-hidden="true">›</span></button>):<p>No dated actions due in the next 7 days.</p>}<small>{summary.undated.length} open action(s) have no due date.</small></section></div>
    <div><section className="portfolio-card"><div className="card-heading"><h2>Data coverage</h2></div><p>Commercial probability <strong>{summary.averageProbability===null?'Not assessed':`${summary.averageProbability}% average`}</strong></p><small>{summary.assessed} of {summary.pipeline.length} active pursuits assessed. This is commercial probability, not construction progress.</small><dl className="coverage-list"><div><dt>Sector recorded</dt><dd>{summary.sectors} / {summary.active.length}</dd></div><div><dt>Source recorded</dt><dd>{summary.sources} / {summary.pipeline.length}</dd></div><div><dt>Unassigned projects</dt><dd>{summary.unassigned.length}</dd></div><div><dt>Risks without severity</dt><dd>{summary.unassessedRisks.length}</dd></div></dl><p className="metric-note">Financial performance, delivery progress and health scoring become available when their governed delivery records are implemented.</p></section></div></div>
  </div>;
}
