import { FormEvent, useCallback, useEffect, useState } from 'react';
import type { ProjectState } from '../../domain/project-state/projectState';
import { projectStageLabel } from '../../domain/project-state/projectState';
import { supabaseProjectStateRepository, type BusinessDispositionView } from '../../infrastructure/project-state/supabaseProjectStateRepository';
import { ProjectStateHistoryWorkspace } from './ProjectStateHistoryWorkspace';
import { WorkspaceModal } from './WorkspaceModal';

const label:Record<BusinessDispositionView,string>={pipeline:'Pipeline',held:'On Hold',inactive:'Inactive'};
const errorText=(e:unknown)=>e instanceof Error?e.message:'Disposition action failed.';
type DispositionAction='hold'|'resume'|'decline'|'withdraw_lost'|'archive'|'restore';
type PendingAction={item:ProjectState;type:DispositionAction};
const actionLabel:Record<DispositionAction,string>={hold:'Hold',resume:'Resume',decline:'Decline',withdraw_lost:'Withdraw / Lost',archive:'Archive',restore:'Restore / Reopen'};
const actionPrompt=(pending:PendingAction)=>pending.type==='hold'?`Why is ${pending.item.name} being placed on hold?`:pending.type==='resume'?`Why is ${pending.item.name} being resumed?`:pending.type==='decline'?`Why is Ridgewood declining ${pending.item.name}?`:pending.type==='withdraw_lost'?`Why was ${pending.item.name} withdrawn or lost?`:pending.type==='archive'?`Why is ${pending.item.name} being administratively archived?`:`Why is ${pending.item.name} being restored to its prior lifecycle stage?`;

export function BusinessDispositionWorkspace({onOpen}:{onOpen:(item:ProjectState)=>void}){
 const[view,setView]=useState<BusinessDispositionView>('pipeline'),[items,setItems]=useState<ProjectState[]>([]),[archived,setArchived]=useState<ProjectState[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[pending,setPending]=useState<PendingAction|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState<string|null>(null);
 const load=useCallback(async(next:BusinessDispositionView)=>{setLoading(true);setError(null);try{const rows=await supabaseProjectStateRepository.list(next);setItems(rows);setArchived(next==='inactive'?await supabaseProjectStateRepository.listArchivedPreauthorization():[])}catch(e){setError(errorText(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load(view)},[load,view]);
 function begin(item:ProjectState,type:DispositionAction){setReason('');setStatus(null);setPending({item,type})}
 function cancel(){if(busy)return;setStatus('Cancelled');window.setTimeout(()=>{setPending(null);setStatus(null)},250)}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!pending||!reason.trim())return;setBusy(true);setStatus(null);try{if(pending.type==='archive')await supabaseProjectStateRepository.archivePreauthorization(pending.item.id,reason.trim());else if(pending.type==='restore')await supabaseProjectStateRepository.restore(pending.item.id,reason.trim());else await supabaseProjectStateRepository.setDisposition(pending.item.id,pending.type,reason.trim());await load(view);setStatus('Saved');window.setTimeout(()=>{setPending(null);setStatus(null)},350)}catch(e){setStatus(errorText(e))}finally{setBusy(false)}}
 function card(item:ProjectState,isArchived=false){return <article className="opportunity-card" key={`${isArchived?'archived-':''}${item.id}`}><button type="button" className="opportunity-card-button" onClick={()=>!isArchived&&onOpen(item)} disabled={isArchived}><strong>{item.name}</strong><span>{projectStageLabel(item.stage)} · {isArchived?'archived':item.status.replaceAll('_',' ')}</span><p>{item.summary||item.nextAction||'No summary recorded.'}</p></button><div className="form-actions">{view==='pipeline'?<><button className="secondary" onClick={()=>begin(item,'hold')}>Hold</button><button className="secondary" onClick={()=>begin(item,'decline')}>Decline</button><button className="secondary" onClick={()=>begin(item,'withdraw_lost')}>Withdraw / Lost</button><button className="secondary" onClick={()=>begin(item,'archive')}>Archive</button></>:null}{view==='held'?<><button onClick={()=>begin(item,'resume')}>Resume</button><button className="secondary" onClick={()=>begin(item,'decline')}>Decline</button><button className="secondary" onClick={()=>begin(item,'withdraw_lost')}>Withdraw / Lost</button><button className="secondary" onClick={()=>begin(item,'archive')}>Archive</button></>:null}{view==='inactive'?<button onClick={()=>begin(item,'restore')}>Restore / Reopen</button>:null}</div><ProjectStateHistoryWorkspace projectStateId={item.id}/></article>}
 return <><section className="panel"><div className="section-heading"><h2>Business</h2><div className="form-actions">{(['pipeline','held','inactive'] as BusinessDispositionView[]).map(v=><button type="button" key={v} className={v===view?'':'secondary'} onClick={()=>setView(v)}>{label[v]}</button>)}</div></div><p>Lifecycle stage and operating disposition are separate. Hold or inactivity preserves the Project State and its existing work. Every material disposition records a rationale.</p>{error?<p className="error-message">{error}</p>:null}{loading?<p>Loading…</p>:<div className="opportunity-list">{items.map(i=>card(i))}{view==='inactive'?archived.map(i=>card(i,true)):null}{!items.length&&!(view==='inactive'&&archived.length)?<p>No {label[view].toLowerCase()} preauthorization Project States.</p>:null}</div>}</section>{pending?<WorkspaceModal title={`${actionLabel[pending.type]} · ${pending.item.name}`} onClose={cancel} busy={busy}><form onSubmit={submit}><p className="guidance">This is a governed lifecycle/disposition action. The rationale is retained in Project State history.</p>{pending.type==='archive'?<p className="guidance">Archiving preserves the Project State and its history in Inactive.</p>:pending.type==='restore'?<p className="guidance">Restoring returns the Project State to its governed prior lifecycle stage.</p>:null}<label><span>{actionPrompt(pending)}</span> <strong className="required-field">Required</strong><textarea required autoFocus value={reason} onChange={e=>setReason(e.target.value)} placeholder="Record the decision rationale."/></label><div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={cancel}>{status==='Cancelled'?'Cancelled':'Cancel'}</button><button type="submit" disabled={busy||!reason.trim()}>{busy?'Saving…':status==='Saved'?'Saved':actionLabel[pending.type]}</button></div>{status&&status!=='Saved'&&status!=='Cancelled'?<p className="error-message" role="alert">{status}</p>:null}</form></WorkspaceModal>:null}</>
}