import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { PredevelopmentDomain, PredevelopmentDomainState, ReadinessState } from '../../domain/predevelopment/predevelopment';
import type { ProjectState } from '../../domain/project-state/projectState';
import { projectStageLabel } from '../../domain/project-state/projectState';
import { developmentObservability } from '../../infrastructure/observability/supabaseDevelopmentObservability';
import { ensurePredevelopmentDomains, listPredevelopmentDomains, updatePredevelopmentDomain } from '../../infrastructure/predevelopment/supabasePredevelopmentRepository';
import { supabaseProjectStateRepository, type ProjectStateStageRequirement } from '../../infrastructure/project-state/supabaseProjectStateRepository';
import { supabaseQualificationRepository, type QualificationArea, type QualificationAssessment, type QualificationDecision, type QualificationFinding } from '../../infrastructure/qualification/supabaseQualificationRepository';

const stages = ['Opportunity', 'Qualification', 'Predevelopment', 'Authorization', 'Project Authorization & Setup'];
const sectors = ['Residential', 'Mixed-use', 'Commercial', 'Industrial', 'Institutional', 'Other'];
const sources = ['Referral', 'Existing relationship', 'Inbound', 'Partner', 'Broker / agent', 'Direct outreach', 'Other'];
const qualification: [QualificationArea, string, string][] = [
  ['opportunity_credibility', 'Opportunity credibility', 'Is the opportunity sufficiently real, identifiable and worth Ridgewood attention?'],
  ['strategic_fit', 'Ridgewood role & strategic fit', 'Does the work fit Ridgewood’s intended role, capabilities and direction?'],
  ['relationship_authority', 'Relationship & authority', 'Do we understand the client, partners, decision-makers and authority path?'],
  ['commercial_plausibility', 'Commercial plausibility', 'Is there a credible commercial path worth developing?'],
  ['execution_risk', 'Execution & risk plausibility', 'Can Ridgewood plausibly deliver the work given the known constraints, risks and capacity?'],
];
const predevelopment: [PredevelopmentDomain, string, string][] = [
  ['development_site', 'Development & site', 'Site, planning, approvals and development constraints'],
  ['product_program', 'Product & program', 'What is being built and for whom'],
  ['design_consultants', 'Design & consultants', 'Required design disciplines and consultant team'],
  ['commercial_feasibility', 'Commercial feasibility', 'Budget, economics, funding and commercial assumptions'],
  ['schedule_phasing', 'Schedule & phasing', 'Timing, milestones and phasing assumptions'],
  ['risk_decision_evidence', 'Risk & evidence', 'Material unknowns, risks and supporting evidence'],
  ['delivery_strategy', 'Delivery strategy', 'Procurement, construction and delivery approach'],
];
const readinessChoices: [ReadinessState, string][] = [['not_started', 'Not started'], ['in_progress', 'In progress'], ['satisfied', 'Satisfied'], ['not_applicable', 'Not applicable'], ['blocked', 'Blocked'], ['unknown', 'Unknown']];
type View = { kind: 'pipeline' } | { kind: 'projectState'; id: string };
function normalizeError(error: unknown, fallback: string): string { if (error instanceof Error) return error.message; if (error && typeof error === 'object') { const value = error as Record<string, unknown>; return [value.message, value.details, value.hint].filter((part) => typeof part === 'string' && part).join(' · ') || fallback; } return fallback; }
function normalize(value?: string): string { return (value ?? '').trim().toLocaleLowerCase(); }
function resolved(readiness?: ReadinessState): boolean { return readiness === 'satisfied' || readiness === 'not_applicable'; }

export function BusinessWorkspace() {
  const [items, setItems] = useState<ProjectState[]>([]); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [error, setError] = useState<string | null>(null); const [view, setView] = useState<View>({ kind: 'pipeline' }); const [draftName, setDraftName] = useState(''); const [duplicateOverride, setDuplicateOverride] = useState(false);
  useEffect(() => { let active = true; void supabaseProjectStateRepository.list().then((next) => { if (active) { setItems(next); setError(null); setLoading(false); } }).catch((caught) => { if (active) { setError(normalizeError(caught, 'Unable to load project states.')); setLoading(false); } }); return () => { active = false; }; }, []);
  const duplicate = useMemo(() => { const candidate = normalize(draftName); if (!candidate || duplicateOverride) return undefined; return items.find((item) => { const existing = normalize(item.name); return existing === candidate || (candidate.length >= 5 && existing.length >= 5 && (existing.includes(candidate) || candidate.includes(existing))); }); }, [draftName, duplicateOverride, items]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const target = event.currentTarget; const form = new FormData(target); const name = String(form.get('name') ?? '').trim(); if (!name || duplicate) return; setCreating(true); setError(null); try { const created = await supabaseProjectStateRepository.create({ name, location: String(form.get('location') ?? '').trim() || undefined, sector: String(form.get('sector') ?? '').trim() || undefined, source: String(form.get('source') ?? '').trim() || undefined, summary: String(form.get('summary') ?? '').trim() || undefined, nextAction: String(form.get('nextAction') ?? '').trim() || undefined, priority: 'medium', commercialStage: 'opportunity' }); setItems((current) => [created, ...current]); target.reset(); setDraftName(''); setDuplicateOverride(false); setView({ kind: 'projectState', id: created.id }); void developmentObservability.capture({ eventName: 'command_succeeded', pagePath: '/business', metadata: { command: 'CreateProjectState', projectStateId: created.id } }); } catch (caught) { setError(normalizeError(caught, 'Project State could not be created.')); } finally { setCreating(false); } }
  async function archive(item: ProjectState) { if (!window.confirm(`Archive ${item.name}? It will be removed from the active pipeline but retained in Ridgewood.`)) return; try { await supabaseProjectStateRepository.archive(item.id); setItems((current) => current.filter((candidate) => candidate.id !== item.id)); setView({ kind: 'pipeline' }); } catch (caught) { setError(normalizeError(caught, 'Project State could not be archived.')); } }
  if (view.kind === 'projectState') { const item = items.find((candidate) => candidate.id === view.id); if (item) return <ProjectStateWorkspace item={item} onChanged={(updated) => setItems((current) => current.map((candidate) => candidate.id === updated.id ? updated : candidate))} onBack={() => setView({ kind: 'pipeline' })} onArchive={() => void archive(item)} />; }
  return <div className="business-grid"><section className="panel"><p className="eyebrow">Gate 2A</p><h2>Business pipeline</h2><p>Create the Project State once. Ridgewood keeps that same identity through qualification, predevelopment and authorization.</p><form className="opportunity-form" onSubmit={create}><label>Working name<input name="name" required value={draftName} onChange={(event) => { setDraftName(event.target.value); setDuplicateOverride(false); }} /></label><label>Site / location <small>optional</small><input name="location" /></label><label>Sector <small>optional</small><select name="sector" defaultValue=""><option value="">Select if known</option>{sectors.map((value) => <option key={value}>{value}</option>)}</select></label><label>Source <small>optional</small><select name="source" defaultValue=""><option value="">Select if known</option>{sources.map((value) => <option key={value}>{value}</option>)}</select></label><label className="wide">Next step <small>optional</small><input name="nextAction" /></label><details className="wide"><summary>Add context</summary><label>Summary <small>optional</small><textarea name="summary" rows={3} /></label></details>{duplicate ? <div className="wide duplicate-warning"><strong>Possible duplicate</strong><p>{duplicate.name} already exists.</p><button type="button" onClick={() => setView({ kind: 'projectState', id: duplicate.id })}>Open existing</button><button type="button" className="secondary" onClick={() => setDuplicateOverride(true)}>Create separate record</button></div> : null}<div className="wide form-actions"><button type="submit" disabled={creating || Boolean(duplicate)}>{creating ? 'Creating…' : 'Create Project State'}</button></div></form>{error ? <p className="error-message">{error}</p> : null}</section><section className="panel"><h2>Active pipeline</h2>{loading ? <p>Loading project states…</p> : items.length === 0 ? <p>No active work yet. Create the first Project State to begin.</p> : <div className="opportunity-list">{items.map((item) => <button type="button" className="opportunity-card opportunity-card-button" key={item.id} onClick={() => setView({ kind: 'projectState', id: item.id })}><div><strong>{item.name}</strong><small>{item.location || 'Location unknown'}</small></div><span>{item.status === 'active' ? projectStageLabel(item.stage) : item.status}</span><p>{item.summary || item.nextAction || 'Open to continue.'}</p></button>)}</div>}</section></div>;
}

function ProjectStateWorkspace({ item, onBack, onArchive, onChanged }: { item: ProjectState; onBack: () => void; onArchive: () => void; onChanged: (item: ProjectState) => void }) {
  const [requirements, setRequirements] = useState<ProjectStateStageRequirement[]>([]); const [findings, setFindings] = useState<QualificationFinding[]>([]); const [domains, setDomains] = useState<PredevelopmentDomainState[]>([]); const [busy, setBusy] = useState(false); const [editingOpportunity, setEditingOpportunity] = useState(false); const [qualificationRationale, setQualificationRationale] = useState(''); const [error, setError] = useState<string | null>(null);
  const opportunity = item.stage === 'opportunity'; const qualificationActive = item.stage === 'qualification'; const predev = item.stage === 'predevelopment'; const authorization = item.stage === 'authorization'; const terminal = item.status !== 'active';
  useEffect(() => { if (opportunity) void supabaseProjectStateRepository.opportunityRequirements(item.id).then(setRequirements).catch((caught) => setError(normalizeError(caught, 'Unable to evaluate Opportunity requirements.'))); }, [item.id, opportunity]);
  useEffect(() => { if (qualificationActive || predev || authorization) void supabaseQualificationRepository.list(item.id).then(setFindings).catch((caught) => setError(normalizeError(caught, 'Unable to load qualification.'))); }, [item.id, qualificationActive, predev, authorization]);
  useEffect(() => { if (predev || authorization) void ensurePredevelopmentDomains(item.id).then(() => listPredevelopmentDomains(item.id)).then(setDomains).catch((caught) => setError(normalizeError(caught, 'Unable to load predevelopment.'))); }, [item.id, predev, authorization]);
  const findingMap = useMemo(() => new Map(findings.map((finding) => [finding.area, finding])), [findings]); const domainMap = useMemo(() => new Map(domains.map((domain) => [domain.domain, domain])), [domains]); const opportunityReady = requirements.length > 0 && requirements.filter((requirement) => requirement.required).every((requirement) => requirement.status === 'satisfied'); const qualificationComplete = qualification.every(([area]) => findingMap.has(area)); const qualificationHasUncertainty = qualification.some(([area]) => { const assessment = findingMap.get(area)?.assessment; return assessment === 'unclear' || assessment === 'no'; }); const advanceRationaleReady = !qualificationHasUncertainty || qualificationRationale.trim().length > 0; const readinessComplete = predevelopment.every(([domain]) => resolved(domainMap.get(domain)?.readiness));
  async function saveOpportunity(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!opportunity || terminal) return; setBusy(true); setError(null); const form = new FormData(event.currentTarget); try { const updated = await supabaseProjectStateRepository.updateOpportunityBasics(item.id, { name: String(form.get('name') ?? '').trim(), location: String(form.get('location') ?? '').trim() || undefined, sector: String(form.get('sector') ?? '').trim() || undefined, source: String(form.get('source') ?? '').trim() || undefined, summary: String(form.get('summary') ?? '').trim() || undefined, nextAction: String(form.get('nextAction') ?? '').trim() || undefined }); onChanged(updated); setRequirements(await supabaseProjectStateRepository.opportunityRequirements(item.id)); setEditingOpportunity(false); } catch (caught) { setError(normalizeError(caught, 'Opportunity information could not be saved.')); } finally { setBusy(false); } }
  async function advanceOpportunity() { if (!opportunityReady || terminal) return; setBusy(true); setError(null); try { onChanged(await supabaseProjectStateRepository.advanceToQualification(item.id)); } catch (caught) { setError(normalizeError(caught, 'Project State could not advance to Qualification.')); } finally { setBusy(false); } }
  async function assess(area: QualificationArea, assessment: QualificationAssessment) { if (terminal || !qualificationActive) return; setBusy(true); try { const finding = { area, assessment }; await supabaseQualificationRepository.save(item.id, finding); setFindings((current) => [...current.filter((value) => value.area !== area), finding]); } catch (caught) { setError(normalizeError(caught, 'Qualification finding could not be saved.')); } finally { setBusy(false); } }
  async function decide(decision: QualificationDecision) { if (terminal || !qualificationActive) return; if (decision === 'advance' && (!qualificationComplete || !advanceRationaleReady)) return; setBusy(true); try { await supabaseQualificationRepository.decide(item.id, decision, qualificationRationale.trim() || undefined); onChanged(decision === 'advance' ? { ...item, stage: 'predevelopment', status: 'active', updatedAt: new Date().toISOString() } : { ...item, status: decision === 'hold' ? 'held' : 'declined', updatedAt: new Date().toISOString() }); } catch (caught) { setError(normalizeError(caught, 'Qualification decision could not be saved.')); } finally { setBusy(false); } }
  async function setReadiness(domain: PredevelopmentDomain, readiness: ReadinessState) { if (!predev || terminal) return; setBusy(true); try { const existing = domainMap.get(domain); await updatePredevelopmentDomain(item.id, domain, readiness, existing?.summary ?? ''); setDomains((current) => current.map((value) => value.domain === domain ? { ...value, readiness, updatedAt: new Date().toISOString() } : value)); } catch (caught) { setError(normalizeError(caught, 'Predevelopment readiness could not be saved.')); } finally { setBusy(false); } }
  async function saveNote(domain: PredevelopmentDomain, note: string) { const existing = domainMap.get(domain); if (!existing || !predev || terminal) return; try { await updatePredevelopmentDomain(item.id, domain, existing.readiness, note); setDomains((current) => current.map((value) => value.domain === domain ? { ...value, summary: note || undefined, updatedAt: new Date().toISOString() } : value)); } catch (caught) { setError(normalizeError(caught, 'Predevelopment note could not be saved.')); } }
  async function enterAuthorization() { if (!predev || !readinessComplete || terminal) return; setBusy(true); setError(null); try { onChanged(await supabaseProjectStateRepository.enterAuthorization(item.id)); } catch (caught) { setError(normalizeError(caught, 'Project State could not enter Authorization.')); } finally { setBusy(false); } }
  const next = terminal ? `This Project State is ${item.status}. No stage work is currently active.` : opportunity ? (opportunityReady ? 'Opportunity requirements are satisfied. Advance to Qualification.' : 'Complete the required Opportunity capture before Qualification.') : qualificationActive ? 'Assess the opportunity. Hold or decline at any point; complete all five domains before advancing.' : predev ? (readinessComplete ? 'Predevelopment requirements are resolved. Enter the Authorization gate.' : 'Resolve the remaining predevelopment requirements.') : authorization ? 'Authorization gate entered. Explicit business authority and protected verification are required to authorize the Project.' : 'Gate 2B work begins after Project Authorization.';
  return <div className="opportunity-workspace"><div className="section-heading"><button type="button" className="text-button" onClick={onBack}>← Active pipeline</button><button type="button" className="text-button danger" onClick={onArchive}>Archive</button></div><section className="panel opportunity-hero"><div><p className="eyebrow">Gate 2A · {item.status === 'active' ? projectStageLabel(item.stage) : item.status}</p><h2>{item.name}</h2><p>{item.location || 'Location not yet recorded'}{item.sector ? ` · ${item.sector}` : ''}</p><small>Project State {item.id}</small></div><div className="next-step"><small>Required next work</small><strong>{next}</strong></div></section><section className="panel"><h3>Gate 2A state</h3><div className="stage-row">{stages.map((stage) => <span key={stage} className={projectStageLabel(item.stage) === stage ? 'active' : ''}>{stage}</span>)}</div></section>
    <section className="panel"><p className="eyebrow">Stage 1</p><h3>Opportunity</h3>{opportunity ? <>{editingOpportunity ? <form className="opportunity-form" onSubmit={saveOpportunity}><label>Working name<input name="name" required defaultValue={item.name} /></label><label>Site / location<input name="location" defaultValue={item.location ?? ''} /></label><label>Sector<select name="sector" defaultValue={item.sector ?? ''}><option value="">Select if known</option>{sectors.map((value) => <option key={value}>{value}</option>)}</select></label><label>Source<select name="source" defaultValue={item.source ?? ''}><option value="">Select if known</option>{sources.map((value) => <option key={value}>{value}</option>)}</select></label><label className="wide">Next step<input name="nextAction" defaultValue={item.nextAction ?? ''} /></label><label className="wide">Summary<textarea name="summary" rows={3} defaultValue={item.summary ?? ''} /></label><div className="wide form-actions"><button disabled={busy} type="submit">Save Opportunity</button><button className="secondary" type="button" onClick={() => setEditingOpportunity(false)}>Cancel</button></div></form> : <><div className="guided-checklist">{requirements.map((requirement) => <article key={requirement.requirementKey}><strong>{requirement.label}</strong><span>{requirement.status.replace('_', ' ')}</span></article>)}</div><div className="form-actions"><button className="secondary" type="button" disabled={busy || terminal} onClick={() => setEditingOpportunity(true)}>Edit Opportunity</button><button type="button" disabled={!opportunityReady || busy || terminal} onClick={() => void advanceOpportunity()}>Advance to qualification</button></div></>}</> : <p className="guidance">Opportunity capture is complete.</p>}</section>
    <section className="panel"><p className="eyebrow">Stage 2</p><h3>Qualification</h3><div className="guided-checklist">{qualification.map(([area, label, help]) => { const current = findingMap.get(area)?.assessment; return <article key={area}><strong>{label}</strong><small>{help}</small><div className="choice-row">{(['yes', 'unclear', 'no'] as QualificationAssessment[]).map((assessment) => <button type="button" key={assessment} disabled={busy || !qualificationActive || terminal} className={current === assessment ? 'active' : ''} onClick={() => void assess(area, assessment)}>{assessment[0].toUpperCase() + assessment.slice(1)}</button>)}</div></article>; })}</div>{qualificationActive && !terminal ? <div className="qualification-decision"><strong>{qualificationComplete ? 'Qualification captured. Advance, hold or decline.' : 'Continue assessing, or hold/decline now if the opportunity should not progress.'}</strong><label>Decision rationale {qualificationHasUncertainty && qualificationComplete ? <small>required to advance while uncertainty or a negative finding remains</small> : <small>optional for hold/decline</small>}<textarea rows={3} value={qualificationRationale} onChange={(event) => setQualificationRationale(event.target.value)} /></label><div className="form-actions"><button type="button" disabled={!qualificationComplete || !advanceRationaleReady || busy} onClick={() => void decide('advance')}>Advance to predevelopment</button><button type="button" className="secondary" disabled={busy} onClick={() => void decide('hold')}>Hold</button><button type="button" className="secondary" disabled={busy} onClick={() => void decide('decline')}>Decline</button></div></div> : null}</section>
    <section className="panel"><p className="eyebrow">Stage 3</p><h3>Predevelopment</h3><div className="readiness-grid">{predevelopment.map(([domain, label, help]) => { const current = domainMap.get(domain); return <article key={domain}><strong>{label}</strong><small>{help}</small>{predev ? <><div className="choice-row">{readinessChoices.map(([state, text]) => <button type="button" key={state} disabled={busy || terminal} className={current?.readiness === state ? 'active' : ''} onClick={() => void setReadiness(domain, state)}>{text}</button>)}</div><details><summary>Add note</summary><textarea rows={2} defaultValue={current?.summary ?? ''} onBlur={(event) => void saveNote(domain, event.currentTarget.value.trim())} /></details></> : <span>{authorization ? 'Predevelopment resolved' : 'Locked until Qualification advances'}</span>}</article>; })}</div>{predev ? <><p className="guidance">{readinessComplete ? 'All required predevelopment domains are resolved. This does not authorize the Project.' : 'Authorization remains locked while a required domain is unresolved. Use Not applicable when a domain genuinely does not apply.'}</p><div className="form-actions"><button type="button" disabled={!readinessComplete || busy || terminal} onClick={() => void enterAuthorization()}>Enter authorization gate</button></div></> : null}</section>
    <section className="panel"><p className="eyebrow">Stage 4</p><h3>Project authorization</h3><p>{authorization ? 'Authorization gate entered. Gate 01 remains fail-closed until explicit permission, scoped business authority, resolved requirements and fresh protected verification are satisfied.' : 'Enter Authorization after Predevelopment requirements are resolved.'}</p><button type="button" disabled>Authorize project</button><small>Final authorization execution will be enabled only through the governed verification path.</small></section>{error ? <p className="error-message" role="alert">{error}</p> : null}</div>;
}
