import { useCallback, useEffect, useState } from 'react';
import type { ProjectState } from '../../domain/project-state/projectState';
import { projectStageLabel } from '../../domain/project-state/projectState';
import { supabaseProjectStateRepository, type BusinessDispositionView } from '../../infrastructure/project-state/supabaseProjectStateRepository';
import { ProjectStateHistoryWorkspace } from './ProjectStateHistoryWorkspace';

const label:Record<BusinessDispositionView,string>={pipeline:'Pipeline',held:'On Hold',inactive:'Inactive'};
const errorText=(e:unknown)=>e instanceof Error?e.message:'Disposition action failed.';
export function BusinessDispositionWorkspace({onOpen}:{onOpen:(item:ProjectState)=>void}){
 const[view,setView]=useState<BusinessDispositionView>('pipeline'),[items,setItems]=useState<ProjectState[]>([]),[archived,setArchived]=useState<ProjectState[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[action,setAction]=useState<string|null>(null);
 const load=useCallback(async(next:BusinessDispositionView)=>{setLoading(true);setError(null);try{const rows=await supabaseProjectStateRepository.list(next);setItems(rows);setArchived(next==='inactive'?await supabaseProjectStateRepository.listArchivedPreauthorization():[])}catch(e){setError(errorText(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load(view)},[load,view]);
 async function disposition(item:ProjectState,type:'hold'|'resume'|'decline'|'withdraw_lost'){const prompts:Record<typeof type,string>={hold:`Reason for placing ${item.name} on hold:`,resume:`Reason for resuming ${item.name}:`,decline:`Reason Ridgewood is declining ${item.name}:`,withdraw_lost:`Reason ${item.name} was withdrawn or lost:`};const reason=window.prompt(prompts[type])?.trim();if(!reason)return;if(!window.confirm(`${type.replaceAll('_',' ')} ${item.name}?`))return;setAction(item.id);try{await supabaseProjectStateRepository.setDisposition(item.id,type,reason);await load(view)}catch(e){setError(errorText(e))}finally{setAction(null)}}
 async function archive(item:ProjectState){const reason=window.prompt(`Administrative reason for archiving ${item.name}:`)?.trim();if(!reason)return;if(!window.confirm(`Archive ${item.name}? Its Project State and history will be preserved in Inactive.`))return;setAction(item.id);try{await supabaseProjectStateRepository.archivePreauthorization(item.id,reason);await load(view)}catch(e){setError(errorText(e))}finally{setAction(null)}}
 async function restore(item:ProjectState){const reason=window.prompt(`Reason for restoring ${item.name}:`)?.trim();if(!reason)return;if(!window.confirm(`Restore ${item.name} to its prior lifecycle stage?`))return;setAction(item.id);try{await supabaseProjectStateRepository.restore(item.id,reason);await load(view)}catch(e){setError(errorText(e))}finally{setAction(null)}}
 function card(item:ProjectState,isArchived=false){return <article className="opportunity-card" key={`${isArchived?'archived-':''}${item.id}`}><button type="button" className="opportunity-card-button" onClick={()=>!isArchived&&onOpen(item)} disabled={isArchived}><strong>{item.name}</strong><span>{projectStageLabel(item.stage)} · {isArchived?'archived':item.status.replaceAll('_',' ')}</span><p>{item.summary||item.nextAction||'No summary recorded.'}</p></button><div className="form-actions">{view==='pipeline'?<><button className="secondary" disabled={action===item.id} onClick={()=>void disposition(item,'hold')}>Hold</button><button className="secondary" disabled={action===item.id} onClick={()=>void disposition(item,'decline')}>Decline</button><button className="secondary" disabled={action===item.id} onClick={()=>void disposition(item,'withdraw_lost')}>Withdraw / Lost</button><button className="secondary" disabled={action===item.id} onClick={()=>void archive(item)}>Archive</button></>:null}{view==='held'?<><button disabled={action===item.id} onClick={()=>void disposition(item,'resume')}>Resume</button><button className="secondary" disabled={action===item.id} onClick={()=>void disposition(item,'decline')}>Decline</button><button className="secondary" disabled={action===item.id} onClick={()=>void disposition(item,'withdraw_lost')}>Withdraw / Lost</button><button className="secondary" disabled={action===item.id} onClick={()=>void archive(item)}>Archive</button></>:null}{view==='inactive'?<button disabled={action===item.id} onClick={()=>void restore(item)}>Restore / Reopen</button>:null}</div><ProjectStateHistoryWorkspace projectStateId={item.id}/></article>}
 return <section className="panel"><div className="section-heading"><h2>Business</h2><div className="form-actions">{(['pipeline','held','inactive'] as BusinessDispositionView[]).map(v=><button type="button" key={v} className={v===view?'':'secondary'} onClick={()=>setView(v)}>{label[v]}</button>)}</div></div><p>Lifecycle stage and operating disposition are separate. Hold or inactivity preserves the Project State and its existing work. Every material disposition records a rationale.</p>{error?<p className="error-message">{error}</p>:null}{loading?<p>Loading…</p>:<div className="opportunity-list">{items.map(i=>card(i))}{view==='inactive'?archived.map(i=>card(i,true)):null}{!items.length&&!(view==='inactive'&&archived.length)?<p>No {label[view].toLowerCase()} preauthorization Project States.</p>:null}</div>}</section>
}