import { useCallback, useEffect, useState } from 'react';
import { createProjectStateEvidence, filterCrossCuttingByContext, listProjectStateCrossCutting, updateProjectStateEvidence, type CrossCuttingEvidence, type KnowledgeState, type LifecycleStage } from '../../infrastructure/cross-cutting/supabaseCrossCuttingRepository';

const knowledgeStates:KnowledgeState[]=['known','unknown','unverified','not_applicable'];

export function CapabilityEvidenceWorkspace({projectStateId,lifecycleStage,capabilityKey,label}:{projectStateId:string;lifecycleStage:LifecycleStage;capabilityKey:string;label:string}){
 const[rows,setRows]=useState<CrossCuttingEvidence[]>([]),[title,setTitle]=useState(''),[sourceSystem,setSourceSystem]=useState('google_drive'),[sourceUrl,setSourceUrl]=useState(''),[note,setNote]=useState(''),[knowledgeState,setKnowledgeState]=useState<KnowledgeState>('known'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const reload=useCallback(async()=>{try{const all=await listProjectStateCrossCutting(projectStateId);setRows(filterCrossCuttingByContext(all,{lifecycleStage,capabilityKey}).evidence);setError(null)}catch(e){setError(e instanceof Error?e.message:'Evidence could not load.')}},[projectStateId,lifecycleStage,capabilityKey]);
 useEffect(()=>{void reload()},[reload]);
 async function add(){setBusy(true);setError(null);try{await createProjectStateEvidence(projectStateId,title,sourceSystem,sourceUrl,note,knowledgeState,{lifecycleStage,capabilityKey});setTitle('');setSourceUrl('');setNote('');setKnowledgeState('known');await reload()}catch(e){setError(e instanceof Error?e.message:'Evidence could not be recorded.')}finally{setBusy(false)}}
 async function setKnowledge(row:CrossCuttingEvidence,value:KnowledgeState){setBusy(true);setError(null);try{await updateProjectStateEvidence({...row,knowledgeState:value});await reload()}catch(e){setError(e instanceof Error?e.message:'Evidence could not be updated.')}finally{setBusy(false)}}
 return <div className="capability-evidence"><div className="document-context"><strong>Governed evidence</strong><span className="status-pill">{rows.length?`${rows.length} linked`:'Not started'}</span><small>Evidence recorded here remains a canonical Project State record linked to {label}; it is not copied into the qualification finding.</small></div>{error?<p className="error-message">{error}</p>:null}<div className="form-grid"><label>Evidence title<input value={title} disabled={busy} onChange={e=>setTitle(e.target.value)} placeholder="Document, source, confirmation or material unknown"/></label><label>Source system<input value={sourceSystem} disabled={busy} onChange={e=>setSourceSystem(e.target.value)}/></label><label>Source reference / URL<input value={sourceUrl} disabled={busy} onChange={e=>setSourceUrl(e.target.value)}/></label><label>Knowledge state<select value={knowledgeState} disabled={busy} onChange={e=>setKnowledgeState(e.target.value as KnowledgeState)}>{knowledgeStates.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label>Provenance / basis note<textarea rows={2} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></label></div><button type="button" disabled={busy||!title.trim()} onClick={()=>void add()}>Add governed evidence</button>{rows.length?<div className="guided-checklist">{rows.map(row=><article key={row.id}><strong>{row.title}</strong><span>{row.sourceSystem} · {row.knowledgeState.replaceAll('_',' ')}</span><select aria-label={`Knowledge state for ${row.title}`} value={row.knowledgeState} disabled={busy} onChange={e=>void setKnowledge(row,e.target.value as KnowledgeState)}>{knowledgeStates.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select>{row.provenanceNote?<small>{row.provenanceNote}</small>:null}</article>)}</div>:null}</div>;
}
