import { useCallback, useEffect, useState } from 'react';
import { createProjectStateAction,createProjectStateEvidence,createProjectStateRiskIssue,filterCrossCuttingByContext,listProjectStateCrossCutting,recordProjectStateDecision,updateProjectStateAction,updateProjectStateEvidence,updateProjectStateRiskIssue,type CrossCuttingAction,type CrossCuttingEvidence,type CrossCuttingRiskIssue,type KnowledgeState,type LifecycleStage,type ProjectStateCrossCutting,type WorkStatus } from '../../infrastructure/cross-cutting/supabaseCrossCuttingRepository';

const empty:ProjectStateCrossCutting={actions:[],risksIssues:[],decisions:[],evidence:[],attention:{level:'clear',reasons:[],overdueActions:0,blockedActions:0,openMaterialRisks:0,unverifiedEvidence:0}};
const statuses:WorkStatus[]=['open','in_progress','blocked','done','cancelled'];
const knowledgeStates:KnowledgeState[]=['known','unknown','unverified','not_applicable'];

type Props={projectStateId:string;lifecycleStage:LifecycleStage;capabilityKey:string;label:string;disabled?:boolean};
export function CapabilityGovernanceWorkspace({projectStateId,lifecycleStage,capabilityKey,label,disabled=false}:Props){
 const[data,setData]=useState<ProjectStateCrossCutting>(empty),[open,setOpen]=useState<'actions'|'risks'|'decisions'|'evidence'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[feedback,setFeedback]=useState<string|null>(null);
 const reload=useCallback(async()=>{try{const all=await listProjectStateCrossCutting(projectStateId);setData(filterCrossCuttingByContext(all,{lifecycleStage,capabilityKey}));setError(null)}catch(e){setError(e instanceof Error?e.message:'Governed capability records could not load.')}},[projectStateId,lifecycleStage,capabilityKey]);
 useEffect(()=>{void reload()},[reload]);
 const run=async(work:()=>Promise<void>,message:string)=>{setBusy(true);setError(null);setFeedback(null);try{await work();await reload();setFeedback(message)}catch(e){setError(e instanceof Error?e.message:'The governed command failed.')}finally{setBusy(false)}};
 const count=data.actions.length+data.risksIssues.length+data.decisions.length+data.evidence.length;
 return <section className="capability-governance"><div className="document-context"><strong>Governed capability records</strong><span className="status-pill">{count?`${count} linked`:'Not started'}</span><small>Canonical Actions, Risks, Decisions and Evidence linked to {label}. Narrative review fields should summarize context rather than duplicate these records.</small></div>{error?<p className="error-message">{error}</p>:null}{feedback?<p className="guidance success">{feedback}</p>:null}<div className="stage-tool-grid"><button type="button" className="secondary" onClick={()=>setOpen(open==='actions'?null:'actions')}>Actions ({data.actions.length})</button><button type="button" className="secondary" onClick={()=>setOpen(open==='risks'?null:'risks')}>Risks / issues ({data.risksIssues.length})</button><button type="button" className="secondary" onClick={()=>setOpen(open==='decisions'?null:'decisions')}>Decisions ({data.decisions.length})</button><button type="button" className="secondary" onClick={()=>setOpen(open==='evidence'?null:'evidence')}>Evidence ({data.evidence.length})</button></div>{open==='actions'?<Actions rows={data.actions} disabled={disabled||busy} add={(title,due)=>run(()=>createProjectStateAction(projectStateId,title,due,{lifecycleStage,capabilityKey}),'Action recorded.')} update={row=>run(()=>updateProjectStateAction(row),'Action updated.')}/>:null}{open==='risks'?<Risks rows={data.risksIssues} disabled={disabled||busy} add={(kind,title,severity)=>run(()=>createProjectStateRiskIssue(projectStateId,kind,title,severity,{lifecycleStage,capabilityKey}),'Risk / issue recorded.')} update={row=>run(()=>updateProjectStateRiskIssue(row),'Risk / issue updated.')}/>:null}{open==='decisions'?<Decisions rows={data.decisions} disabled={disabled||busy} add={(type,outcome,rationale,authority)=>run(()=>recordProjectStateDecision(projectStateId,type,outcome,rationale,authority,{lifecycleStage,capabilityKey}),'Decision recorded.')}/>:null}{open==='evidence'?<Evidence rows={data.evidence} disabled={disabled||busy} add={(title,system,url,note,state)=>run(()=>createProjectStateEvidence(projectStateId,title,system,url,note,state,{lifecycleStage,capabilityKey}),'Evidence recorded.')} update={row=>run(()=>updateProjectStateEvidence(row),'Evidence updated.')}/>:null}</section>;
}
function Actions({rows,disabled,add,update}:{rows:CrossCuttingAction[];disabled:boolean;add:(title:string,due?:string)=>Promise<void>;update:(row:CrossCuttingAction)=>Promise<void>}){const[title,setTitle]=useState(''),[due,setDue]=useState('');return <div className="stage-tool-surface"><div className="form-grid"><label>Action<input value={title} disabled={disabled} onChange={e=>setTitle(e.target.value)}/></label><label>Due date<input type="date" value={due} disabled={disabled} onChange={e=>setDue(e.target.value)}/></label></div><button type="button" disabled={disabled||!title.trim()} onClick={()=>void add(title,due||undefined).then(()=>{setTitle('');setDue('')})}>Add action</button>{rows.map(row=><article key={row.id}><strong>{row.title}</strong><select value={row.status} disabled={disabled} onChange={e=>void update({...row,status:e.target.value as WorkStatus})}>{statuses.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></article>)}</div>}
function Risks({rows,disabled,add,update}:{rows:CrossCuttingRiskIssue[];disabled:boolean;add:(kind:string,title:string,severity?:string)=>Promise<void>;update:(row:CrossCuttingRiskIssue)=>Promise<void>}){const[kind,setKind]=useState('risk'),[title,setTitle]=useState(''),[severity,setSeverity]=useState('');return <div className="stage-tool-surface"><div className="form-grid"><label>Type<select value={kind} disabled={disabled} onChange={e=>setKind(e.target.value)}><option value="risk">Risk</option><option value="issue">Issue</option></select></label><label>Title<input value={title} disabled={disabled} onChange={e=>setTitle(e.target.value)}/></label><label>Severity<select value={severity} disabled={disabled} onChange={e=>setSeverity(e.target.value)}><option value="">Not assessed</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label></div><button type="button" disabled={disabled||!title.trim()} onClick={()=>void add(kind,title,severity||undefined).then(()=>{setTitle('');setSeverity('')})}>Add risk / issue</button>{rows.map(row=><article key={row.id}><strong>{row.title}</strong><select value={row.status} disabled={disabled} onChange={e=>void update({...row,status:e.target.value as WorkStatus})}>{statuses.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></article>)}</div>}
function Decisions({rows,disabled,add}:{rows:ProjectStateCrossCutting['decisions'];disabled:boolean;add:(type:string,outcome:string,rationale?:string,authority?:string)=>Promise<void>}){const[type,setType]=useState('decision'),[outcome,setOutcome]=useState(''),[rationale,setRationale]=useState(''),[authority,setAuthority]=useState('');return <div className="stage-tool-surface"><p className="guidance">Decisions are append-only. Record a new decision rather than overwriting history.</p><div className="form-grid"><label>Type<input value={type} disabled={disabled} onChange={e=>setType(e.target.value)}/></label><label>Outcome<input value={outcome} disabled={disabled} onChange={e=>setOutcome(e.target.value)}/></label><label>Rationale<textarea value={rationale} disabled={disabled} onChange={e=>setRationale(e.target.value)}/></label><label>Authority basis<textarea value={authority} disabled={disabled} onChange={e=>setAuthority(e.target.value)}/></label></div><button type="button" disabled={disabled||!type.trim()||!outcome.trim()} onClick={()=>void add(type,outcome,rationale||undefined,authority||undefined).then(()=>{setOutcome('');setRationale('');setAuthority('')})}>Record decision</button>{rows.map(row=><article key={row.id}><strong>{row.decisionType}</strong><span>{row.outcome}</span></article>)}</div>}
function Evidence({rows,disabled,add,update}:{rows:CrossCuttingEvidence[];disabled:boolean;add:(title:string,system:string,url:string,note:string,state:KnowledgeState)=>Promise<void>;update:(row:CrossCuttingEvidence)=>Promise<void>}){const[title,setTitle]=useState(''),[system,setSystem]=useState('google_drive'),[url,setUrl]=useState(''),[note,setNote]=useState(''),[state,setState]=useState<KnowledgeState>('known');return <div className="stage-tool-surface"><div className="form-grid"><label>Evidence title<input value={title} disabled={disabled} onChange={e=>setTitle(e.target.value)}/></label><label>Source system<input value={system} disabled={disabled} onChange={e=>setSystem(e.target.value)}/></label><label>Source reference / URL<input value={url} disabled={disabled} onChange={e=>setUrl(e.target.value)}/></label><label>Knowledge state<select value={state} disabled={disabled} onChange={e=>setState(e.target.value as KnowledgeState)}>{knowledgeStates.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label>Provenance / basis<textarea value={note} disabled={disabled} onChange={e=>setNote(e.target.value)}/></label></div><button type="button" disabled={disabled||!title.trim()} onClick={()=>void add(title,system,url,note,state).then(()=>{setTitle('');setUrl('');setNote('');setState('known')})}>Add evidence</button>{rows.map(row=><article key={row.id}><strong>{row.title}</strong><select value={row.knowledgeState} disabled={disabled} onChange={e=>void update({...row,knowledgeState:e.target.value as KnowledgeState})}>{knowledgeStates.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></article>)}</div>}
