import { FormEvent, useEffect, useMemo, useState } from 'react';
import { type ProjectStateDocumentRevision } from '../../infrastructure/documents/supabaseDocumentRepository';
import { useGovernedProjectStateDocument } from './useGovernedProjectStateDocument';

type DeliveryData={deliveryModel:string;procurementStrategy:string;contractingStrategy:string;constructionApproach:string;workPackaging:string;rolesResponsibilities:string;tradeMarketStrategy:string;logisticsMobilization:string;qualityStrategy:string;safetyStrategy:string;commercialControls:string;unknowns:string;blockers:string;evidenceReferences:string;decisions:string;notes:string};
const empty:DeliveryData={deliveryModel:'',procurementStrategy:'',contractingStrategy:'',constructionApproach:'',workPackaging:'',rolesResponsibilities:'',tradeMarketStrategy:'',logisticsMobilization:'',qualityStrategy:'',safetyStrategy:'',commercialControls:'',unknowns:'',blockers:'',evidenceReferences:'',decisions:'',notes:''};
const text=(v:unknown)=>typeof v==='string'?v:'';
const fromData=(d:Record<string,unknown>):DeliveryData=>({deliveryModel:text(d.deliveryModel),procurementStrategy:text(d.procurementStrategy),contractingStrategy:text(d.contractingStrategy),constructionApproach:text(d.constructionApproach),workPackaging:text(d.workPackaging),rolesResponsibilities:text(d.rolesResponsibilities),tradeMarketStrategy:text(d.tradeMarketStrategy),logisticsMobilization:text(d.logisticsMobilization),qualityStrategy:text(d.qualityStrategy),safetyStrategy:text(d.safetyStrategy),commercialControls:text(d.commercialControls),unknowns:text(d.unknowns),blockers:text(d.blockers),evidenceReferences:text(d.evidenceReferences),decisions:text(d.decisions),notes:text(d.notes)});
const definition={packageKey:'predevelopment',category:'delivery_strategy',documentType:'predevelopment_delivery_strategy',title:'Delivery Strategy Review'};

export function DeliveryStrategyWorkspace({projectStateId,projectName,disabled=false,onChanged}:{projectStateId:string;projectName:string;disabled?:boolean;onChanged?:()=>void}){
 const doc=useGovernedProjectStateDocument(projectStateId,definition),[values,setValues]=useState<DeliveryData>(empty),[editing,setEditing]=useState(false),[historyOpen,setHistoryOpen]=useState(false),active=doc.draft??doc.published;
 useEffect(()=>{setValues(active?fromData(active.data):empty);setEditing(Boolean(doc.draft)||!doc.published)},[active,doc.draft,doc.published]);
 const canEdit=!disabled&&(Boolean(doc.draft)||!doc.published||editing);
 const blockers=useMemo(()=>{const b:string[]=[];if(!values.deliveryModel.trim())b.push('Delivery model');if(!values.procurementStrategy.trim())b.push('Procurement strategy');if(!values.contractingStrategy.trim())b.push('Contracting strategy');if(!values.constructionApproach.trim())b.push('Construction approach');if(!values.rolesResponsibilities.trim())b.push('Roles and responsibilities');return b},[values]);
 const set=(key:keyof DeliveryData,value:string)=>setValues(v=>({...v,[key]:value}));
 const field=(key:keyof DeliveryData,label:string,required=false,rows=3)=><label>{label}<small className={required?'field-requirement required':'field-requirement'}>{required?'Required':'Optional'}</small><textarea rows={rows} value={values[key]} disabled={!canEdit||Boolean(doc.busy)} onChange={e=>set(key,e.target.value)}/></label>;
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canEdit||doc.busy)return;try{await doc.save(values);onChanged?.()}catch(error){doc.setError(error instanceof Error?error.message:'Save failed.')}}
 async function publish(){if(!canEdit||doc.busy)return;doc.setError(null);if(blockers.length){doc.setError(`Cannot publish yet. Complete: ${blockers.join(', ')}.`);return}const note=doc.published?window.prompt('What changed? Briefly explain this revision.'):undefined;if(doc.published&&!note?.trim()){doc.setError('A change note is required for revision 2 and later.');return}if(!window.confirm(`Publish ${doc.draft?`revision ${doc.draft.revisionNumber}`:'Delivery Strategy Review'}?`))return;try{await doc.publish(values,note??undefined);setEditing(false);onChanged?.()}catch(error){doc.setError(error instanceof Error?error.message:'Publish failed.')}}
 async function revise(){try{await doc.createRevision();setEditing(true);onChanged?.()}catch(error){doc.setError(error instanceof Error?error.message:'Revision could not be created.')}}
 async function discard(){if(!doc.draft||!window.confirm('Discard this draft? Unsaved revision work will be removed.'))return;try{await doc.discard();onChanged?.()}catch(error){doc.setError(error instanceof Error?error.message:'Draft could not be discarded.')}}
 function cancel(){if(!window.confirm('Cancel editing? Changes since the last save will be lost.'))return;setValues(active?fromData(active.data):empty);setEditing(Boolean(doc.draft)||!doc.published)}
 if(doc.loading)return <div className="document-workspace"><p>Loading Delivery Strategy Review…</p></div>;
 const status=doc.draft?'Incomplete':doc.published?'Complete':'Not started';
 return <div className="document-workspace"><div className="document-context"><strong>Delivery Strategy Review</strong><span className="status-pill">{status}</span><small>{projectName} · Project State {projectStateId}</small></div><p className="guidance">Define how Ridgewood intends to procure, contract, mobilize and deliver the project. Capture the current strategy and unresolved delivery assumptions without prematurely creating downstream Project-stage records.</p>{doc.draft?<div className="revision-banner"><strong>Revision {doc.draft.revisionNumber} draft</strong><span>Working copy</span></div>:null}<form className="structured-form" onSubmit={save}>
 <fieldset><legend>Delivery model</legend>{field('deliveryModel','Delivery model / project delivery method',true,3)}{field('contractingStrategy','Contracting strategy / commercial relationship',true,3)}{field('constructionApproach','Construction approach / sequencing concept',true,4)}{field('rolesResponsibilities','Ridgewood, owner and key-party roles / responsibilities',true,4)}</fieldset>
 <fieldset><legend>Procurement and market</legend>{field('procurementStrategy','Procurement strategy',true,4)}{field('workPackaging','Anticipated work packages / tender structure',false,4)}{field('tradeMarketStrategy','Trade / supplier market strategy and capacity',false,4)}</fieldset>
 <fieldset><legend>Mobilization and controls</legend>{field('logisticsMobilization','Mobilization / site logistics approach',false,4)}{field('qualityStrategy','Quality management approach',false,3)}{field('safetyStrategy','Safety / compliance approach',false,3)}{field('commercialControls','Delivery-stage commercial / change-control approach',false,3)}</fieldset>
 <fieldset><legend>Uncertainty and evidence</legend>{field('unknowns','Known unknowns / assumptions requiring confirmation',false,3)}{field('blockers','Blockers / unresolved delivery constraints',false,3)}{field('evidenceReferences','Evidence / source references',false,3)}{field('decisions','Delivery decisions / assumptions adopted',false,3)}{field('notes','Project-specific notes',false,3)}</fieldset>
 {canEdit&&blockers.length?<div className="blocking-summary"><strong>Publication incomplete</strong><p>{blockers.length} required item(s) remain: {blockers.join(', ')}.</p></div>:canEdit?<p className="guidance success">Required information complete. Ready to publish.</p>:null}{doc.error?<p className="error-message" role="alert">{doc.error}</p>:null}{doc.feedback?<p className="guidance success">{doc.feedback}</p>:null}<div className="form-actions">{canEdit?<><button type="submit" disabled={Boolean(doc.busy)}>{doc.busy==='save'?'Saving…':'Save draft'}</button><button type="button" disabled={Boolean(doc.busy)} onClick={()=>void publish()}>{doc.busy==='publish'?'Publishing…':'Publish'}</button><button type="button" className="secondary" disabled={Boolean(doc.busy)} onClick={cancel}>Cancel</button>{doc.draft?<button type="button" className="secondary" disabled={Boolean(doc.busy)} onClick={()=>void discard()}>Discard draft</button>:null}</>:doc.published?<button type="button" disabled={disabled||Boolean(doc.busy)} onClick={()=>void revise()}>{doc.busy==='revision'?'Creating revision…':'Edit'}</button>:null}</div></form>{doc.published?<Published revision={doc.published}/>:null}{doc.history.length?<div className="revision-history"><button type="button" className="text-button" onClick={()=>setHistoryOpen(v=>!v)}>{historyOpen?'Hide':'Show'} revision history ({doc.history.length})</button>{historyOpen?doc.history.map(r=><article key={r.revisionId}><strong>Revision {r.revisionNumber}</strong><span>{r.state}</span><small>{r.publishedAt?new Date(r.publishedAt).toLocaleString():''} · {r.changeNote||'Initial publication'}</small></article>):null}</div>:null}</div>
}
function Published({revision}:{revision:ProjectStateDocumentRevision}){return <div className="published-summary"><strong>Published revision {revision.revisionNumber}</strong><small>{revision.publishedAt?new Date(revision.publishedAt).toLocaleString():''} · {revision.changeNote||'Initial publication'}</small></div>}
