import { FormEvent, useEffect, useMemo, useState } from 'react';
import { type ProjectStateDocumentRevision } from '../../infrastructure/documents/supabaseDocumentRepository';
import { useGovernedProjectStateDocument } from './useGovernedProjectStateDocument';

type RiskData={materialRisks:string;riskResponses:string;materialUnknowns:string;assumptions:string;openDecisions:string;decisionOwners:string;evidenceRequired:string;evidenceReferences:string;exceptions:string;authorizationConditions:string;blockers:string;notes:string};
const empty:RiskData={materialRisks:'',riskResponses:'',materialUnknowns:'',assumptions:'',openDecisions:'',decisionOwners:'',evidenceRequired:'',evidenceReferences:'',exceptions:'',authorizationConditions:'',blockers:'',notes:''};
const text=(v:unknown)=>typeof v==='string'?v:'';
const fromData=(d:Record<string,unknown>):RiskData=>({materialRisks:text(d.materialRisks),riskResponses:text(d.riskResponses),materialUnknowns:text(d.materialUnknowns),assumptions:text(d.assumptions),openDecisions:text(d.openDecisions),decisionOwners:text(d.decisionOwners),evidenceRequired:text(d.evidenceRequired),evidenceReferences:text(d.evidenceReferences),exceptions:text(d.exceptions),authorizationConditions:text(d.authorizationConditions),blockers:text(d.blockers),notes:text(d.notes)});
const definition={packageKey:'predevelopment',category:'risk_decision_evidence',documentType:'predevelopment_risk_decision_evidence',title:'Risk, Decision & Evidence Review'};

export function RiskDecisionEvidenceWorkspace({projectStateId,projectName,disabled=false,onChanged}:{projectStateId:string;projectName:string;disabled?:boolean;onChanged?:()=>void}){
 const doc=useGovernedProjectStateDocument(projectStateId,definition),[values,setValues]=useState<RiskData>(empty),[editing,setEditing]=useState(false),[historyOpen,setHistoryOpen]=useState(false),active=doc.draft??doc.published;
 useEffect(()=>{setValues(active?fromData(active.data):empty);setEditing(Boolean(doc.draft)||!doc.published)},[active,doc.draft,doc.published]);
 const canEdit=!disabled&&(Boolean(doc.draft)||!doc.published||editing);
 const blockers=useMemo(()=>{const b:string[]=[];if(!values.materialRisks.trim())b.push('Material risks');if(!values.materialUnknowns.trim())b.push('Material unknowns');if(!values.openDecisions.trim())b.push('Open decisions');if(!values.evidenceRequired.trim())b.push('Evidence required');return b},[values]);
 const set=(key:keyof RiskData,value:string)=>setValues(v=>({...v,[key]:value}));
 const field=(key:keyof RiskData,label:string,required=false,rows=3)=><label>{label}<small className={required?'field-requirement required':'field-requirement'}>{required?'Required':'Optional'}</small><textarea rows={rows} value={values[key]} disabled={!canEdit||Boolean(doc.busy)} onChange={e=>set(key,e.target.value)}/></label>;
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canEdit||doc.busy)return;try{await doc.save(values);onChanged?.()}catch(error){doc.setError(error instanceof Error?error.message:'Save failed.')}}
 async function publish(){if(!canEdit||doc.busy)return;doc.setError(null);if(blockers.length){doc.setError(`Cannot publish yet. Complete: ${blockers.join(', ')}.`);return}const note=doc.published?window.prompt('What changed? Briefly explain this revision.'):undefined;if(doc.published&&!note?.trim()){doc.setError('A change note is required for revision 2 and later.');return}if(!window.confirm(`Publish ${doc.draft?`revision ${doc.draft.revisionNumber}`:'Risk, Decision & Evidence Review'}?`))return;try{await doc.publish(values,note??undefined);setEditing(false);onChanged?.()}catch(error){doc.setError(error instanceof Error?error.message:'Publish failed.')}}
 async function revise(){try{await doc.createRevision();setEditing(true);onChanged?.()}catch(error){doc.setError(error instanceof Error?error.message:'Revision could not be created.')}}
 async function discard(){if(!doc.draft||!window.confirm('Discard this draft? Unsaved revision work will be removed.'))return;try{await doc.discard();onChanged?.()}catch(error){doc.setError(error instanceof Error?error.message:'Draft could not be discarded.')}}
 function cancel(){if(!window.confirm('Cancel editing? Changes since the last save will be lost.'))return;setValues(active?fromData(active.data):empty);setEditing(Boolean(doc.draft)||!doc.published)}
 if(doc.loading)return <div className="document-workspace"><p>Loading Risk, Decision & Evidence Review…</p></div>;
 const status=doc.draft?'Incomplete':doc.published?'Complete':'Not started';
 return <div className="document-workspace"><div className="document-context"><strong>Risk, Decision & Evidence Review</strong><span className="status-pill">{status}</span><small>{projectName} · Project State {projectStateId}</small></div><p className="guidance">Consolidate the material uncertainty that could change the authorization decision. Record risks, unknowns, decisions and supporting evidence explicitly; this review does not replace the underlying governed records.</p>{doc.draft?<div className="revision-banner"><strong>Revision {doc.draft.revisionNumber} draft</strong><span>Working copy</span></div>:null}<form className="structured-form" onSubmit={save}>
 <fieldset><legend>Risks and uncertainty</legend>{field('materialRisks','Material risks / issues',true,4)}{field('riskResponses','Mitigation / response strategy',false,4)}{field('materialUnknowns','Material unknowns',true,4)}{field('assumptions','Material assumptions',false,3)}</fieldset>
 <fieldset><legend>Decisions</legend>{field('openDecisions','Open / required decisions',true,4)}{field('decisionOwners','Decision owners / required authority',false,3)}{field('exceptions','Exceptions / deviations requiring acceptance',false,3)}{field('authorizationConditions','Potential authorization conditions',false,3)}</fieldset>
 <fieldset><legend>Evidence</legend>{field('evidenceRequired','Evidence required to support readiness / decisions',true,4)}{field('evidenceReferences','Available evidence / source references',false,4)}{field('blockers','Blocking evidence gaps / unresolved conditions',false,3)}</fieldset>
 <fieldset><legend>Notes</legend>{field('notes','Project-specific notes',false,3)}</fieldset>
 {canEdit&&blockers.length?<div className="blocking-summary"><strong>Publication incomplete</strong><p>{blockers.length} required item(s) remain: {blockers.join(', ')}.</p></div>:canEdit?<p className="guidance success">Required information complete. Ready to publish.</p>:null}{doc.error?<p className="error-message" role="alert">{doc.error}</p>:null}{doc.feedback?<p className="guidance success">{doc.feedback}</p>:null}<div className="form-actions">{canEdit?<><button type="submit" disabled={Boolean(doc.busy)}>{doc.busy==='save'?'Saving…':'Save draft'}</button><button type="button" disabled={Boolean(doc.busy)} onClick={()=>void publish()}>{doc.busy==='publish'?'Publishing…':'Publish'}</button><button type="button" className="secondary" disabled={Boolean(doc.busy)} onClick={cancel}>Cancel</button>{doc.draft?<button type="button" className="secondary" disabled={Boolean(doc.busy)} onClick={()=>void discard()}>Discard draft</button>:null}</>:doc.published?<button type="button" disabled={disabled||Boolean(doc.busy)} onClick={()=>void revise()}>{doc.busy==='revision'?'Creating revision…':'Edit'}</button>:null}</div></form>{doc.published?<Published revision={doc.published}/>:null}{doc.history.length?<div className="revision-history"><button type="button" className="text-button" onClick={()=>setHistoryOpen(v=>!v)}>{historyOpen?'Hide':'Show'} revision history ({doc.history.length})</button>{historyOpen?doc.history.map(r=><article key={r.revisionId}><strong>Revision {r.revisionNumber}</strong><span>{r.state}</span><small>{r.publishedAt?new Date(r.publishedAt).toLocaleString():''} · {r.changeNote||'Initial publication'}</small></article>):null}</div>:null}</div>
}
function Published({revision}:{revision:ProjectStateDocumentRevision}){return <div className="published-summary"><strong>Published revision {revision.revisionNumber}</strong><small>{revision.publishedAt?new Date(revision.publishedAt).toLocaleString():''} · {revision.changeNote||'Initial publication'}</small></div>}
