import { FormEvent, useEffect, useMemo, useState } from 'react';
import { type ProjectStateDocumentRevision } from '../../infrastructure/documents/supabaseDocumentRepository';
import { useGovernedProjectStateDocument } from './useGovernedProjectStateDocument';

type ScheduleData={scheduleBasis:string;targetStart:string;targetCompletion:string;keyMilestones:string;phasingStrategy:string;criticalDependencies:string;approvalsLeadTimes:string;procurementLeadTimes:string;constraints:string;floatContingency:string;unknowns:string;blockers:string;evidenceReferences:string;decisions:string;notes:string};
const empty:ScheduleData={scheduleBasis:'',targetStart:'',targetCompletion:'',keyMilestones:'',phasingStrategy:'',criticalDependencies:'',approvalsLeadTimes:'',procurementLeadTimes:'',constraints:'',floatContingency:'',unknowns:'',blockers:'',evidenceReferences:'',decisions:'',notes:''};
const text=(v:unknown)=>typeof v==='string'?v:'';
const fromData=(d:Record<string,unknown>):ScheduleData=>({scheduleBasis:text(d.scheduleBasis),targetStart:text(d.targetStart),targetCompletion:text(d.targetCompletion),keyMilestones:text(d.keyMilestones),phasingStrategy:text(d.phasingStrategy),criticalDependencies:text(d.criticalDependencies),approvalsLeadTimes:text(d.approvalsLeadTimes),procurementLeadTimes:text(d.procurementLeadTimes),constraints:text(d.constraints),floatContingency:text(d.floatContingency),unknowns:text(d.unknowns),blockers:text(d.blockers),evidenceReferences:text(d.evidenceReferences),decisions:text(d.decisions),notes:text(d.notes)});
const definition={packageKey:'predevelopment',category:'schedule_phasing',documentType:'predevelopment_schedule_phasing',title:'Schedule & Phasing Review'};

export function SchedulePhasingWorkspace({projectStateId,projectName,disabled=false,onChanged}:{projectStateId:string;projectName:string;disabled?:boolean;onChanged?:()=>void}){
 const doc=useGovernedProjectStateDocument(projectStateId,definition),[values,setValues]=useState<ScheduleData>(empty),[editing,setEditing]=useState(false),[historyOpen,setHistoryOpen]=useState(false),active=doc.draft??doc.published;
 useEffect(()=>{setValues(active?fromData(active.data):empty);setEditing(Boolean(doc.draft)||!doc.published)},[active?.revisionId,doc.draft?.revisionId,doc.published?.revisionId]);
 const canEdit=!disabled&&(Boolean(doc.draft)||!doc.published||editing);
 const blockers=useMemo(()=>{const b:string[]=[];if(!values.scheduleBasis.trim())b.push('Schedule basis');if(!values.targetStart.trim())b.push('Target start');if(!values.targetCompletion.trim())b.push('Target completion');if(!values.keyMilestones.trim())b.push('Key milestones');if(!values.criticalDependencies.trim())b.push('Critical dependencies');return b},[values]);
 const set=(key:keyof ScheduleData,value:string)=>setValues(v=>({...v,[key]:value}));
 const field=(key:keyof ScheduleData,label:string,required=false,rows=2)=><label>{label}<small className={required?'field-requirement required':'field-requirement'}>{required?'Required':'Optional'}</small><textarea rows={rows} value={values[key]} disabled={!canEdit||Boolean(doc.busy)} onChange={e=>set(key,e.target.value)}/></label>;
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canEdit||doc.busy)return;try{await doc.save(values);onChanged?.()}catch{}}
 async function publish(){if(!canEdit||doc.busy)return;doc.setError(null);if(blockers.length){doc.setError(`Cannot publish yet. Complete: ${blockers.join(', ')}.`);return}const note=doc.published?window.prompt('What changed? Briefly explain this revision.'):undefined;if(doc.published&&!note?.trim()){doc.setError('A change note is required for revision 2 and later.');return}if(!window.confirm(`Publish ${doc.draft?`revision ${doc.draft.revisionNumber}`:'Schedule & Phasing Review'}?`))return;try{await doc.publish(values,note??undefined);setEditing(false);onChanged?.()}catch{}}
 async function revise(){try{await doc.createRevision();setEditing(true);onChanged?.()}catch{}}
 async function discard(){if(!doc.draft||!window.confirm('Discard this draft? Unsaved revision work will be removed.'))return;try{await doc.discard();onChanged?.()}catch{}}
 function cancel(){if(!window.confirm('Cancel editing? Changes since the last save will be lost.'))return;setValues(active?fromData(active.data):empty);setEditing(Boolean(doc.draft)||!doc.published)}
 if(doc.loading)return <div className="document-workspace"><p>Loading Schedule & Phasing Review…</p></div>;
 const status=doc.draft?'Incomplete':doc.published?'Complete':'Not started';
 return <div className="document-workspace"><div className="document-context"><strong>Schedule & Phasing Review</strong><span className="status-pill">{status}</span><small>{projectName} · Project State {projectStateId}</small></div><p className="guidance">Establish whether the proposed timing is credible. Capture assumptions, dependencies and lead times explicitly; dates are planning evidence, not commitments unless separately authorized.</p>{doc.draft?<div className="revision-banner"><strong>Revision {doc.draft.revisionNumber} draft</strong><span>Working copy</span></div>:null}<form className="structured-form" onSubmit={save}>
 <fieldset><legend>Schedule basis</legend>{field('scheduleBasis','Schedule basis / assumptions',true,3)}{field('targetStart','Target start / mobilization',true)}{field('targetCompletion','Target completion / occupancy',true)}{field('keyMilestones','Key milestones',true,4)}</fieldset>
 <fieldset><legend>Phasing and dependencies</legend>{field('phasingStrategy','Phasing strategy',false,3)}{field('criticalDependencies','Critical dependencies / predecessor conditions',true,4)}{field('approvalsLeadTimes','Approvals / permitting lead times',false,3)}{field('procurementLeadTimes','Long-lead procurement / consultant dependencies',false,3)}</fieldset>
 <fieldset><legend>Constraints and resilience</legend>{field('constraints','Schedule constraints / restricted windows',false,3)}{field('floatContingency','Float / contingency assumptions',false,3)}{field('unknowns','Known unknowns',false,3)}{field('blockers','Blockers / unresolved timing risks',false,3)}{field('evidenceReferences','Evidence / source references',false,3)}</fieldset>
 <fieldset><legend>Decisions and notes</legend>{field('decisions','Decisions / assumptions adopted',false,3)}{field('notes','Project-specific notes',false,3)}</fieldset>
 {canEdit&&blockers.length?<div className="blocking-summary"><strong>Publication incomplete</strong><p>{blockers.length} required item(s) remain: {blockers.join(', ')}.</p></div>:canEdit?<p className="guidance success">Required information complete. Ready to publish.</p>:null}{doc.error?<p className="error-message" role="alert">{doc.error}</p>:null}{doc.feedback?<p className="guidance success">{doc.feedback}</p>:null}<div className="form-actions">{canEdit?<><button type="submit" disabled={Boolean(doc.busy)}>{doc.busy==='save'?'Saving…':'Save draft'}</button><button type="button" disabled={Boolean(doc.busy)} onClick={()=>void publish()}>{doc.busy==='publish'?'Publishing…':'Publish'}</button><button type="button" className="secondary" disabled={Boolean(doc.busy)} onClick={cancel}>Cancel</button>{doc.draft?<button type="button" className="secondary" disabled={Boolean(doc.busy)} onClick={()=>void discard()}>Discard draft</button>:null}</>:doc.published?<button type="button" disabled={disabled||Boolean(doc.busy)} onClick={()=>void revise()}>{doc.busy==='revision'?'Creating revision…':'Edit'}</button>:null}</div></form>{doc.published?<Published revision={doc.published}/>:null}{doc.history.length?<div className="revision-history"><button type="button" className="text-button" onClick={()=>setHistoryOpen(v=>!v)}>{historyOpen?'Hide':'Show'} revision history ({doc.history.length})</button>{historyOpen?doc.history.map(r=><article key={r.revisionId}><strong>Revision {r.revisionNumber}</strong><span>{r.state}</span><small>{r.publishedAt?new Date(r.publishedAt).toLocaleString():''} · {r.changeNote||'Initial publication'}</small></article>):null}</div>:null}</div>
}
function Published({revision}:{revision:ProjectStateDocumentRevision}){return <div className="published-summary"><strong>Published revision {revision.revisionNumber}</strong><small>{revision.publishedAt?new Date(revision.publishedAt).toLocaleString():''} · {revision.changeNote||'Initial publication'}</small></div>}
