import { ChangeProposal } from './ChangeProposal';
import { useEffect, useRef, useState } from 'react';
import { blankChange, changeRepository, ChangeCommandError, type ChangeData, type ChangeDecision, type ChangeDimension, type ChangeState } from '../../infrastructure/project-state/changeRepository';
import { createRequestId } from '../../infrastructure/project-state/requestId';
import { PublishedDocumentView } from '../business/PublishedDocumentView';
import { WorkspaceModal } from '../business/WorkspaceModal';
import { useDrawerWorkState } from '../business/WorkspaceDrawer';

export function ChangeAssessment({projectStateId,changeId,blocked}:{projectStateId:string;changeId:string;blocked:boolean}){
 const [open,setOpen]=useState(false);
 return <><button disabled={blocked} onClick={()=>setOpen(true)}>Review change assessment</button>{open&&<WorkspaceModal title="5.3.5 Changes — Assessment & Internal Review" onClose={()=>setOpen(false)}><ChangeEditor projectStateId={projectStateId} changeId={changeId}/></WorkspaceModal>}</>;
}
function ChangeEditor({projectStateId,changeId}:{projectStateId:string;changeId:string}){
 const [state,setState]=useState<ChangeState|null>(null),[data,setData]=useState(blankChange),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [dimension,setDimension]=useState<ChangeDimension|''>(''),[authorityId,setAuthorityId]=useState(''),[outcome,setOutcome]=useState<ChangeDecision['outcome']|''>(''),[rationale,setRationale]=useState(''),[confirmed,setConfirmed]=useState(false);
 const pending=useRef<{kind:'save'|'request';id:string;version:number;data:ChangeData}|{kind:'decide';input:ChangeDecision}|null>(null);
 const reviewDirty=Boolean(dimension||authorityId||outcome||rationale||confirmed);
 useDrawerWorkState(dirty||reviewDirty||Boolean(pending.current),busy);
 function loaded(s:ChangeState){setState(s);setData(s.data??blankChange());}
 useEffect(()=>{let active=true;changeRepository.read(projectStateId,changeId).then(s=>{if(active)loaded(s);}).catch(()=>{if(active)setError('Change assessment could not load. Try again.');});return()=>{active=false;};},[projectStateId,changeId]);
 function clearReview(){setDimension('');setAuthorityId('');setOutcome('');setRationale('');setConfirmed(false);}
 async function reload(){if((dirty||reviewDirty||pending.current)&&!window.confirm('Discard unsaved change entries and reload the saved assessment?'))return;setBusy(true);try{loaded(await changeRepository.read(projectStateId,changeId));setDirty(false);clearReview();pending.current=null;setError('');setMessage('Saved change assessment loaded.');}catch{setError('Change assessment could not load. Try again.');}finally{setBusy(false);}}
 function patch(p:Partial<ChangeData>){setData(d=>({...d,...p}));setDirty(true);setMessage('');}
 async function command(kind:'save'|'request'|'decide'){
  if(!state||busy)return;
  if(kind==='decide'&&!pending.current&&!window.confirm(`Record the ${dimension} internal review? This does not authorize instructions, spending, baseline changes or changed work.`))return;
  setBusy(true);setError('');setMessage('');
  try{
   if(!pending.current){if(kind==='decide'){if(!dimension||!outcome)return;pending.current={kind,input:{id:createRequestId(),version:state.version,dimension,sequence:state.dimensions[dimension].sequence,authorityId,outcome,rationale,confirmed}};}else pending.current={kind,id:createRequestId(),version:state.version,data:structuredClone(data)};}
   const r=pending.current;
   const s=r.kind==='decide'?await changeRepository.decide(projectStateId,changeId,r.input):r.kind==='save'?await changeRepository.save(projectStateId,changeId,r.version,r.id,r.data):await changeRepository.request(projectStateId,changeId,r.version,r.id);
   pending.current=null;loaded(s);setDirty(false);clearReview();setMessage(r.kind==='save'?`Saved change assessment version ${s.savedVersion}.`:r.kind==='request'?`Internal review requested for version ${s.submittedVersion}.`:r.kind==='decide'?`${r.input.dimension[0].toUpperCase()+r.input.dimension.slice(1)} internal decision recorded. No changed work authorized.`:'Saved.');
  }catch(e){if(e instanceof ChangeCommandError&&e.code==='P0001')pending.current=null;
   const messages:Record<string,string>={invalid_change_money:'Enter a signed cost amount with at most two decimal places.',invalid_change_days:'Enter a signed whole number of days.',invalid_change_currency:'Enter a three-letter currency code.',invalid_change_sources:'Choose current published impact evidence from this project.',incomplete_change_assessment:'Complete and save the assessment, including the original baseline, before requesting review.',change_version_conflict:'The assessment changed. Reload before continuing.',change_review_sequence_conflict:'Another decision was recorded. Reload before reviewing.',change_owner_authority_required:'Verified current owner authority is required.',missing_change_review_permission:'Change review permission is required.',change_strong_verification_required:'Recent strong verification is required.',change_approval_basis_unresolved:'Resolve the saved assessment blockers before approval.',change_dimension_confirmation_required:'Confirm the selected dimension independently before approval.'};
   setError(`${messages[e instanceof Error?e.message:'']??'The change command could not be saved.'} ${pending.current?'Retry preserves the exact request.':'Your entries remain here.'}`);
  }finally{setBusy(false);}
 }
 if(!state)return <>{error?<><p role="alert">{error}</p><button disabled={busy} onClick={()=>void reload()}>Retry loading change</button></>:<p>Loading change assessment…</p>}</>;
 const locked=busy||!state.canEdit||Boolean(pending.current),required=<span className="setup-required">Required for review</span>;
 return <section className="stage-tool-surface contract-review change-assessment">
 <p>Assess this departure once in Changes. Scope retains its original baseline; scope, cost and time require independent internal decisions. Client and trade authorization, instructions and implementation remain separate.</p>
 <p>Original scope baseline: {state.baseline?`version ${state.baseline.version}`:'Not established'}. Change reference: {state.changeId}.</p>
 <details><summary>Originating scope question</summary><p>{state.origin.question}</p><p>{state.origin.response}</p><p>Saved scope version {state.origin.scopeVersion} · Identified {state.origin.identifiedOn} · Owner {state.origin.ownerUserId}</p></details>
 <fieldset disabled={locked||reviewDirty}>
 <label>Change description {required}<textarea value={data.description} maxLength={500} onChange={e=>patch({description:e.target.value})}/><small>Example: Add a threshold excluded from the approved flooring scope. Describe what changes and what stays within the original boundary.</small></label>
 <label>Proposed scope version {required}<select value={data.proposedScopeVersion} onChange={e=>patch({proposedScopeVersion:e.target.value})}><option value="">Select a saved scope preparation</option>{state.scopeHistory.map(s=><option key={s.version} value={s.version}>Version {s.version} · {s.items.length} components</option>)}</select><small>Prepare the proposed components in 5.3 Scope first. This reference cannot overwrite the original baseline.</small></label>
 <label>Cost assessment {required}<select value={data.costAssessment} onChange={e=>patch({costAssessment:e.target.value as ChangeData['costAssessment']})}><option value="">Unassessed</option><option value="assessed">Assessed — amount supported by evidence</option></select></label>
 <label>Signed cost impact {required}<input type="number" step="0.01" value={data.costAmount} onChange={e=>patch({costAmount:e.target.value})}/><small>Example: 1250.00 additional cost, -250.00 credit, or an explicitly reviewed 0.00. Blank means unknown. This is an assessment, not a budget or commitment update.</small></label>
 <label>Impact currency {required}<input value={data.currency} maxLength={3} placeholder="Example: USD" onChange={e=>patch({currency:e.target.value.toUpperCase()})}/></label>
 <label>Time assessment {required}<select value={data.timeAssessment} onChange={e=>patch({timeAssessment:e.target.value as ChangeData['timeAssessment']})}><option value="">Unassessed</option><option value="assessed">Assessed — signed days supported by evidence</option></select></label>
 <label>Signed time impact in days {required}<input type="number" step="1" value={data.timeDays} onChange={e=>patch({timeDays:e.target.value})}/><small>Example: 3 additional days, -2 days saved, or explicitly reviewed 0 days. Cost approval cannot approve time.</small></label>
 <label>Time calendar basis {required}<select value={data.calendarBasis} onChange={e=>patch({calendarBasis:e.target.value as ChangeData['calendarBasis']})}><option value="">Select the assessment basis</option><option value="working_days">Working days</option><option value="calendar_days">Calendar days</option></select></label>
 <label>Assessment assumptions <span className="optional-label">Optional if none</span><textarea maxLength={4000} value={data.assumptions} onChange={e=>patch({assumptions:e.target.value})}/><small>Explain pricing inclusions, exclusions, productivity and schedule assumptions that apply.</small></label>
 <label>Other impacts and notice implications {required}<textarea maxLength={4000} value={data.otherImpacts} onChange={e=>patch({otherImpacts:e.target.value})}/><small>Assess procurement, quality, safety, permits, responsibilities and notices. Explain an assessed absence of impact; do not leave unknown items implicit.</small></label>
 <label>Material blocker assessment {required}<select value={data.materialAssessment} onChange={e=>patch({materialAssessment:e.target.value as ChangeData['materialAssessment']})}><option value="">Unassessed</option><option value="none_identified">Reviewed — no material blocker identified</option><option value="identified">Material blocker or exception identified</option></select><small>An identified blocker cannot be waived by this internal review.</small></label>
 <div className="contract-choices"><p>Published impact and pricing evidence {required}</p>{state.sources.filter(s=>s.state==='published').map(s=><label key={s.id}><input type="checkbox" checked={data.basisRevisionIds.includes(s.id)} onChange={e=>patch({basisRevisionIds:e.target.checked?[...data.basisRevisionIds,s.id]:data.basisRevisionIds.filter(id=>id!==s.id)})}/><span>{s.label}</span></label>)}</div>
 </fieldset>
 <p role="status" aria-label="Change assessment status">{message||`Saved change assessment version ${state.version}`}{dirty?' · Unsaved changes':''}</p>{error&&<p role="alert">{error}</p>}
 <h4>Request exact-version internal review</h4><ul aria-label="Change assessment blockers">{state.blockers.map(b=><li key={b}>{b}</li>)}</ul>
 <button disabled={locked||dirty||reviewDirty||state.version===0||state.requests.some(r=>r.version===state.version)} onClick={()=>void command('request')}>Request change internal review</button>
 {pending.current?.kind==='request'&&<button disabled={busy} onClick={()=>void command('request')}>Retry change review request</button>}
 <ul aria-label="Change review requests">{state.requests.map(r=><li key={r.id}>Version {r.version} · {r.status} request</li>)}</ul>
 <h4>Independent internal decisions</h4><ul aria-label="Change dimension status">{(['scope','cost','time'] as const).map(d=><li key={d}>{d}: {state.dimensions[d].current?'approved internally':state.dimensions[d].outcome?`${state.dimensions[d].outcome} — current approval required`:'not reviewed'}</li>)}</ul>
 <p>Verified owner evidence, change review permission and recent strong verification are required. A decision covers only the selected dimension of this exact assessment.</p>
 <fieldset disabled={busy||dirty||Boolean(pending.current)||!state.canEdit||!state.reviewAccess.hasPermission}>
 <label>Review dimension {required}<select value={dimension} onChange={e=>{setDimension(e.target.value as ChangeDimension|'');setConfirmed(false);}}><option value="">Select one dimension</option><option value="scope">Scope</option><option value="cost">Cost</option><option value="time">Time</option></select></label>
 <label>Change owner authority {required}<select value={authorityId} onChange={e=>setAuthorityId(e.target.value)}><option value="">Select verified owner evidence</option>{state.reviewAccess.ownerAuthorities.map(a=><option key={a.id} value={a.id}>{a.reference}</option>)}</select></label>
 <label>Internal decision {required}<select value={outcome} onChange={e=>setOutcome(e.target.value as typeof outcome)}><option value="">Select an outcome</option><option value="approved">Approve selected dimension internally</option><option value="held">Hold</option><option value="rejected">Reject</option></select></label>
 <label>Change decision rationale {required}<textarea value={rationale} maxLength={4000} onChange={e=>setRationale(e.target.value)}/></label>
 <div className="contract-choices"><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed the selected {dimension||'dimension'} impact and its evidence independently. No material blocker is waived and no changed work, instruction or spending is authorized. <span className="setup-required">Required for approval</span></span></label></div>
 </fieldset>
 <button disabled={busy||dirty||!state.canEdit||!state.reviewAccess.hasPermission||!dimension||!outcome||!authorityId||!rationale.trim()||Boolean(pending.current&&pending.current.kind!=='decide')} onClick={()=>void command('decide')}>{pending.current?.kind==='decide'?'Retry change decision':'Record change internal decision'}</button>
 <ChangeProposal projectStateId={projectStateId} changeId={changeId} blocked={dirty||reviewDirty||busy||Boolean(pending.current)}/><h4>Execution remains blocked</h4><p>{state.internalApproved?'All three dimensions have current internal approval.':'Independent internal review remains incomplete.'}</p><ul>{state.executionBlockers.map(b=><li key={b}>{b}</li>)}</ul>
 <h4>Assessment and decision history</h4>{state.history.map(h=><details key={h.version}><summary>Change assessment version {h.version} · {new Date(h.createdAt).toLocaleString()}</summary><p>{h.data.description}</p><p>Proposed scope version {h.data.proposedScopeVersion||'not supplied'} · Cost {h.data.costAssessment||'unassessed'}: {h.data.costAmount||'unknown'} {h.data.currency} · Time {h.data.timeAssessment||'unassessed'}: {h.data.timeDays||'unknown'} {h.data.calendarBasis}</p><p>Assumptions: {h.data.assumptions||'None supplied'}</p><p>Other impacts: {h.data.otherImpacts||'Not supplied'}</p><p>Material assessment: {h.data.materialAssessment||'Unassessed'}</p>{h.references.map(r=><details key={r.id}><summary>{r.title} · revision {r.revisionNumber}</summary><PublishedDocumentView revision={{documentId:r.documentId,revisionId:r.id,revisionNumber:r.revisionNumber,state:'published',title:r.title,documentType:r.documentType,category:r.category,packageKey:'',data:r.published_source_snapshot,snapshotAvailable:true,publishedAt:r.publishedAt,publishedBy:r.publishedBy,createdAt:'',changeNote:null,changes:[]}}/></details>)}</details>)}
 <ul aria-label="Change decision history">{state.decisions.map(d=><li key={d.id}>Version {d.version} · {d.dimension} · {d.outcome}<p>{d.rationale}</p><p>{d.authorityReference} · {new Date(d.createdAt).toLocaleString()} · {d.actorUserId}</p></li>)}</ul>
 <div className="setup-actions"><button disabled={busy||!state.canEdit||reviewDirty||Boolean(pending.current&&pending.current.kind!=='save')} onClick={()=>void command('save')}>{pending.current?.kind==='save'?'Retry change assessment save':'Save change assessment'}</button><button disabled={busy} onClick={()=>void reload()}>Reload saved change</button></div>
 </section>;
}
