import { useEffect, useRef, useState } from 'react';
import { blankProposal, proposalRepository, ProposalCommandError, type ProposalData, type ProposalDecision, type ProposalSource, type ProposalState } from '../../infrastructure/project-state/changeProposalRepository';
import { createRequestId } from '../../infrastructure/project-state/requestId';
import { WorkspaceModal } from '../business/WorkspaceModal';
import { useDrawerWorkState } from '../business/WorkspaceDrawer';
import { PublishedDocumentView } from '../business/PublishedDocumentView';
export function ChangeProposal({projectStateId,changeId,blocked}:{projectStateId:string;changeId:string;blocked:boolean}){
 const [open,setOpen]=useState(false);
 return <><button disabled={blocked} onClick={()=>setOpen(true)}>5.3.6 Client Change Proposal</button>{open&&<WorkspaceModal title="5.3.6 Client Change Proposal" onClose={()=>setOpen(false)}><ProposalEditor projectStateId={projectStateId} changeId={changeId}/></WorkspaceModal>}</>;
}
function ProposalPublication({source}:{source:ProposalSource}){return <PublishedDocumentView revision={{documentId:source.documentId,revisionId:source.revisionId,revisionNumber:source.revisionNumber,state:'published',title:source.title,documentType:source.documentType,category:source.category,packageKey:'',data:source.payload,snapshotAvailable:true,publishedAt:source.publishedAt,publishedBy:source.publishedBy,createdAt:'',changeNote:null,changes:[]}}/>;}
function ProposalEditor({projectStateId,changeId}:{projectStateId:string;changeId:string}){
 const [state,setState]=useState<ProposalState|null>(null),[data,setData]=useState(blankProposal),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [authorityId,setAuthorityId]=useState(''),[outcome,setOutcome]=useState<ProposalDecision['outcome']|''>(''),[rationale,setRationale]=useState(''),[confirmed,setConfirmed]=useState(false);
 const pending=useRef<{kind:'save';id:string;version:number;assessmentVersion:number;data:ProposalData}|{kind:'decide';input:ProposalDecision}|null>(null);
 const reviewDirty=Boolean(authorityId||outcome||rationale||confirmed);useDrawerWorkState(dirty||reviewDirty||Boolean(pending.current),busy);
 function loaded(s:ProposalState){setState(s);setData(s.data??blankProposal());}
 function clearReview(){setAuthorityId('');setOutcome('');setRationale('');setConfirmed(false);}
 useEffect(()=>{let active=true;proposalRepository.read(projectStateId,changeId).then(s=>{if(active)loaded(s);}).catch(()=>{if(active)setError('Proposal could not load. Try again.');});return()=>{active=false;};},[projectStateId,changeId]);
 async function reload(){if((dirty||reviewDirty||pending.current)&&!window.confirm('Discard unsaved proposal entries and load the saved record?'))return;setBusy(true);try{loaded(await proposalRepository.read(projectStateId,changeId));pending.current=null;clearReview();setDirty(false);setError('');setMessage('Saved proposal loaded.');}catch{setError('Proposal could not load. Try again.');}finally{setBusy(false);}}
 function patch(p:Partial<ProposalData>){setData(d=>({...d,...p}));setDirty(true);setMessage('');}
 async function command(kind:'save'|'decide'){
  if(!state||busy)return;
  if(kind==='decide'&&!pending.current&&!window.confirm('Record this exact proposal release decision? It sends no message and records no client acceptance, trade approval or instruction to work.'))return;
  setBusy(true);setError('');setMessage('');
  try{
   if(!pending.current){if(kind==='decide'){if(!outcome)return;pending.current={kind,input:{id:createRequestId(),version:state.version,sequence:state.sequence,authorityId,outcome,rationale,confirmed}};}else pending.current={kind,id:createRequestId(),version:state.version,assessmentVersion:state.basisVersion,data:structuredClone(data)};}
   const r=pending.current;const s=r.kind==='save'?await proposalRepository.save(projectStateId,changeId,r.assessmentVersion,r.version,r.id,r.data):await proposalRepository.decide(projectStateId,changeId,r.input);
   pending.current=null;loaded(s);clearReview();setDirty(false);setMessage(r.kind==='save'?`Saved client proposal version ${s.savedVersion}.`:'Proposal release decision recorded. Client acceptance and work authorization remain separate.');
  }catch(e){if(e instanceof ProposalCommandError&&e.code==='P0001')pending.current=null;
   const errors:Record<string,string>={invalid_proposal_amount:'Enter a signed client amount with at most two decimal places.',invalid_proposal_date:'Enter a valid calendar date or leave it blank if no fixed expiry applies.',invalid_proposal_recipient:'Select an active organization from this workspace.',invalid_proposal_publication:'Select a current published proposal from this project.',change_proposal_version_conflict:'Another proposal was saved. Reload before continuing.',change_version_conflict:'The assessment changed. Reload before saving against its latest version.',proposal_decision_sequence_conflict:'Another release decision was recorded. Reload before continuing.',proposal_release_basis_unresolved:'Resolve the saved proposal blockers before authorizing release.',proposal_confirmation_required:'Verify and confirm the exact client proposal before release.',proposal_owner_authority_required:'Verified effective owner authority is required.',proposal_strong_verification_required:'Recent strong verification is required.',missing_proposal_release_permission:'Explicit proposal-release permission is required.'};
   setError(`${errors[e instanceof Error?e.message:'']??'The proposal command could not be saved.'} ${pending.current?'Retry preserves the exact request.':'Your entries remain here.'}`);
  }finally{setBusy(false);}
 }
 if(!state)return <>{error?<><p role="alert">{error}</p><button disabled={busy} onClick={()=>void reload()}>Retry loading proposal</button></>:<p>Loading client proposal…</p>}</>;
 const required=<span className="setup-required">Required for release</span>,locked=busy||!state.canEdit||Boolean(pending.current);
 return <section className="stage-tool-surface contract-review change-proposal">
 <p>A client quotation is a separate commercial offer. Reference the approved assessment and exact published proposal; do not substitute internal cost for the client price.</p>
 <p>Referenced assessment version: {state.basisVersion}. Cost: {state.basis?.costAmount||'Unassessed'} {state.basis?.currency}. Proposed scope version: {state.basis?.proposedScopeVersion||'Not supplied'}. Time: {state.basis?.timeDays||'Unknown'} {state.basis?.calendarBasis}. These facts are maintained in Changes assessment.</p>
 <p>Assessment assumptions: {state.basis?.assumptions||'None supplied'}. Other impacts: {state.basis?.otherImpacts||'Not supplied'}.</p>
 {state.basisVersion!==state.assessment.version&&<button disabled={locked||reviewDirty} onClick={()=>{if(window.confirm('Start a new proposal against the current assessment? Re-enter client price and offer terms; the earlier proposal stays in history.')){setState({...state,basis:state.assessment.data,basisVersion:state.assessment.version});setData(blankProposal());setDirty(true);setMessage('Prepare new commercial terms against the current assessment.');}}}>Prepare proposal against current assessment</button>}
 <fieldset disabled={locked||reviewDirty}>
 <label>Client recipient {required}<select value={data.recipientPartyId} onChange={e=>patch({recipientPartyId:e.target.value})}><option value="">Select the client organization</option>{state.parties.filter(p=>!p.retired||p.id===data.recipientPartyId).map(p=><option key={p.id} value={p.id} disabled={p.retired}>{p.label}{p.retired?' · Retired':''}</option>)}</select><small>The recipient must be a party to the current reviewed contract. Owner review verifies its client role; directory membership alone is insufficient.</small></label>
 <label>Proposed client amount ({state.basis?.currency||'assessment currency unresolved'}) {required}<input type="number" step="0.01" value={data.clientAmount} onChange={e=>patch({clientAmount:e.target.value})}/><small>Enter the proposed price or credit, including an explicit zero where reviewed. Currency comes from the referenced assessment; no exchange conversion or budget update occurs here.</small></label>
 <label>Markup and fee treatment {required}<textarea maxLength={4000} value={data.feeTreatment} onChange={e=>patch({feeTreatment:e.target.value})}/><small>Example: Assessed cost plus the contract fee shown in the quotation; identify inclusions, credits and any concession. Explain a reviewed absence of markup.</small></label>
 <label>Client commercial terms {required}<textarea maxLength={4000} value={data.commercialTerms} onChange={e=>patch({commercialTerms:e.target.value})}/><small>Explain offer-specific assumptions, exclusions, payment/tax treatment, validity and conditions. Reference assessment facts instead of entering a second scope or time delta.</small></label>
 <label>Exact published client proposal {required}<select value={data.proposalRevisionId} onChange={e=>patch({proposalRevisionId:e.target.value})}><option value="">Select a current published revision</option>{state.assessment.sources.filter(s=>s.state==='published').map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><small>The owner must verify this exact document matches the recipient, price, fee, conditions and separately reviewed scope/time basis. Publication itself does not authorize release.</small></label>
 <label>Proposal valid through <span className="optional-label">Optional if no fixed expiry</span><input type="date" value={data.validUntil} onChange={e=>patch({validUntil:e.target.value})}/><small>If no fixed date applies, state the validity rule in commercial terms. An expired date blocks a new release.</small></label>
 </fieldset>
 {error&&<p role="alert">{error}</p>}<p role="status" aria-label="Client proposal status">{message||`Saved client proposal version ${state.version}`}{dirty?' · Unsaved changes':''}</p>
 <h4>Owner decision to release the proposal</h4><ul aria-label="Proposal blockers">{state.blockers.map(b=><li key={b}>{b}</li>)}</ul>
 <fieldset disabled={locked||dirty||!state.reviewAccess.hasPermission}>
 <label>Proposal owner authority {required}<select value={authorityId} onChange={e=>setAuthorityId(e.target.value)}><option value="">Select verified owner evidence</option>{state.reviewAccess.ownerAuthorities.map(a=><option key={a.id} value={a.id}>{a.reference}</option>)}</select></label>
 <label>Proposal release outcome {required}<select value={outcome} onChange={e=>setOutcome(e.target.value as typeof outcome)}><option value="">Select an outcome</option><option value="approved">Authorize this exact proposal for release</option><option value="held">Hold</option><option value="rejected">Reject</option></select></label>
 <label>Proposal decision reason {required}<textarea value={rationale} maxLength={4000} onChange={e=>setRationale(e.target.value)}/></label>
 <div className="contract-choices"><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I verified the recipient is the contract client and the exact proposal matches the price, markup/fee, commercial conditions and independently approved scope/time. No material exception is waived. <span className="setup-required">Required to authorize release</span></span></label></div>
 </fieldset>
 <button disabled={busy||dirty||!state.canEdit||!state.reviewAccess.hasPermission||state.version===0||!authorityId||!outcome||!rationale.trim()||Boolean(pending.current&&pending.current.kind!=='decide')} onClick={()=>void command('decide')}>{pending.current?.kind==='decide'?'Retry proposal release decision':'Record proposal release decision'}</button>
 <p aria-label="Proposal release state">{state.releaseAuthorized?'Current proposal release is owner-authorized.':'Current proposal release is not authorized.'} No message has been sent. Client acceptance, trade approval and an authorized work instruction remain outstanding.</p>
 {state.sourceSnapshot?.revisionId&&<details><summary>View saved proposal publication</summary><ProposalPublication source={state.sourceSnapshot}/></details>}
 <h4>Proposal history</h4>{state.history.map(h=><details key={h.version}><summary>Client proposal version {h.version} · Assessment {h.assessmentVersion}</summary><p>Client: {h.sourceSnapshot.recipient?.label||h.data.recipientPartyId||'Not selected'} · Proposed amount: {h.data.clientAmount||'Unknown'} {h.basis.currency}</p><p>{h.data.feeTreatment||'Fee treatment not supplied'}</p><p>{h.data.commercialTerms||'Commercial terms not supplied'}</p><p>Valid through: {h.data.validUntil||'No fixed date supplied; consult commercial terms'}</p><p>Scope version {h.basis.proposedScopeVersion} · Time {h.basis.timeDays} {h.basis.calendarBasis}</p>{h.sourceSnapshot.revisionId&&<ProposalPublication source={h.sourceSnapshot}/>}</details>)}
 <ul aria-label="Proposal decision history">{state.decisions.map(d=><li key={d.id}>Proposal {d.version} · {d.outcome}<p>{d.rationale}</p><p>{d.authorityReference} · {new Date(d.createdAt).toLocaleString()} · {d.actorUserId}</p></li>)}</ul>
 <div className="setup-actions"><button disabled={busy||!state.canEdit||reviewDirty||state.assessment.version===0||Boolean(pending.current&&pending.current.kind!=='save')} onClick={()=>void command('save')}>{pending.current?.kind==='save'?'Retry client proposal save':'Save client proposal'}</button><button disabled={busy} onClick={()=>void reload()}>Reload saved proposal</button></div>
 </section>;
}
