import { useEffect, useState } from 'react';
import type { ProjectState } from '../../domain/project-state/projectState';
import { projectStageLabel } from '../../domain/project-state/projectState';
import { supabaseProjectStateRepository, type AuthorizationRecordSummary } from '../../infrastructure/project-state/supabaseProjectStateRepository';

function countSnapshot(record:AuthorizationRecordSummary,key:string){const snapshot=record.evidenceSnapshot;if(!snapshot||typeof snapshot!=='object')return 0;const value=(snapshot as Record<string,unknown>)[key];return Array.isArray(value)?value.length:0}
function AuthorizationRecord({projectStateId}:{projectStateId:string}){const[record,setRecord]=useState<AuthorizationRecordSummary|null>(null),[open,setOpen]=useState(false),[error,setError]=useState<string|null>(null);useEffect(()=>{let active=true;supabaseProjectStateRepository.authorizationRecord(projectStateId).then(v=>{if(active)setRecord(v)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Authorization record could not load.')});return()=>{active=false}},[projectStateId]);if(error)return <small className="error-message">{error}</small>;if(!record)return <small>Authorization record loading…</small>;return <div className="authorization-handoff"><button className="secondary-button" onClick={()=>setOpen(!open)}>{open?'Hide':'View'} Pre-Authorization / Authorization Record</button>{open?<div className="stage-tool-surface"><h4>Frozen authorization record</h4><p className="guidance">This is the historical decision basis captured when authorization succeeded. It is read-only and remains attached to this same Project State.</p><div className="guided-checklist"><article><strong>Outcome</strong><span>{record.outcome}</span></article><article><strong>Authorized</strong><span>{new Date(record.createdAt).toLocaleString()}</span></article><article><strong>Authority basis</strong><span>{record.authorityBasis||'Recorded by governed authorization command'}</span></article><article><strong>Published preauthorization documents</strong><span>{countSnapshot(record,'publishedDocuments')}</span></article><article><strong>Evidence references</strong><span>{countSnapshot(record,'evidenceReferences')}</span></article><article><strong>Decisions / approvals</strong><span>{countSnapshot(record,'decisions')}</span></article><article><strong>Authorization conditions</strong><span>{countSnapshot(record,'authorizationConditions')}</span></article></div></div>:null}</div>}

export function ProjectsWorkspace(){
 const[items,setItems]=useState<ProjectState[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;supabaseProjectStateRepository.listProjects().then(v=>{if(active){setItems(v);setLoading(false)}}).catch(e=>{if(active){setError(e instanceof Error?e.message:'Unable to load authorized projects.');setLoading(false)}});return()=>{active=false}},[]);
 return <section className="panel"><h2>Authorized projects</h2><p>Project States move here when Project Authorization succeeds. The same identity continues into delivery while the exact pre-authorization decision record remains frozen for reference.</p>{error?<p className="error-message">{error}</p>:null}{loading?<p>Loading…</p>:items.length?<div className="opportunity-list">{items.map(item=><article className="opportunity-card" key={item.id}><strong>{item.name}</strong><span>{projectStageLabel(item.stage)}</span><p>{item.summary||item.nextAction||'Authorized Ridgewood project.'}</p><AuthorizationRecord projectStateId={item.id}/></article>)}</div>:<p>No authorized projects yet.</p>}</section>;
}