import { useEffect, useState } from 'react';
import type { ProjectState } from '../../domain/project-state/projectState';
import { projectStageLabel } from '../../domain/project-state/projectState';
import { supabaseProjectStateRepository, type AuthorizationAmendmentSummary, type AuthorizationRecordSummary } from '../../infrastructure/project-state/supabaseProjectStateRepository';
import { WorkspaceModal } from '../business/WorkspaceModal';

function countSnapshot(record:AuthorizationRecordSummary,key:string){const snapshot=record.evidenceSnapshot;if(!snapshot||typeof snapshot!=='object')return 0;const value=(snapshot as Record<string,unknown>)[key];return Array.isArray(value)?value.length:0}
function AuthorizationRecord({projectStateId}:{projectStateId:string}){
 const[record,setRecord]=useState<AuthorizationRecordSummary|null>(null),[amendments,setAmendments]=useState<AuthorizationAmendmentSummary[]>([]),[open,setOpen]=useState(false),[error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;Promise.all([supabaseProjectStateRepository.authorizationRecord(projectStateId),supabaseProjectStateRepository.authorizationAmendments(projectStateId)]).then(([authorization,history])=>{if(active){setRecord(authorization);setAmendments(history)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Authorization record could not load.')});return()=>{active=false}},[projectStateId]);
 if(error)return <small className="error-message">{error}</small>;if(!record)return <small>Authorization record loading…</small>;
 return <div className="authorization-handoff"><button className="secondary-button" onClick={()=>setOpen(true)}>View Pre-Authorization / Authorization Record</button>{open?<WorkspaceModal title="Pre-Authorization / Authorization Record" onClose={()=>setOpen(false)}><div className="stage-tool-surface"><h4>Frozen authorization record</h4><p className="guidance">This is the historical decision basis captured when authorization succeeded. It is read-only and remains attached to this same Project State. Corrections and addenda are appended below and never rewrite this baseline.</p><div className="guided-checklist"><article><strong>Outcome</strong><span>{record.outcome}</span></article><article><strong>Authorized</strong><span>{new Date(record.createdAt).toLocaleString()}</span></article><article><strong>Authority basis</strong><span>{record.authorityBasis||'Recorded by governed authorization command'}</span></article><article><strong>Published preauthorization documents</strong><span>{countSnapshot(record,'publishedDocuments')}</span></article><article><strong>Evidence references</strong><span>{countSnapshot(record,'evidenceReferences')}</span></article><article><strong>Decisions / approvals</strong><span>{countSnapshot(record,'decisions')}</span></article><article><strong>Authorization conditions</strong><span>{countSnapshot(record,'authorizationConditions')}</span></article></div><h4>Correction / addendum history</h4><p className="guidance">Governed amendments preserve the original authorization record. Evidence corrections identify the exact authorized document revision and changed fields; addenda append governed context without rewriting the frozen baseline.</p>{amendments.length?<div className="guided-checklist">{amendments.map(a=><article key={a.id}><strong>{a.amendmentType==='correction'?'Correction':'Addendum'} · {new Date(a.createdAt).toLocaleString()}</strong><span>{a.summary}</span><small>{a.rationale}{a.documentRecordId&&a.originalRevisionId?` · Document ${a.documentRecordId.slice(0,8)} · revision ${a.originalRevisionId.slice(0,8)} · ${Object.keys(a.changedFields??{}).length} changed field(s)`:''}</small></article>)}</div>:<small>No post-authorization amendments recorded.</small>}</div></WorkspaceModal>:null}</div>}

export function ProjectsWorkspace(){
 const [items,setItems]=useState<ProjectState[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[archived,setArchived]=useState(false),[archiving,setArchiving]=useState<string|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError(null);supabaseProjectStateRepository.listProjects(archived).then(v=>{if(active)setItems(v)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load projects.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[archived]);
 async function archive(item:ProjectState){
  if(!window.confirm(`Archive “${item.name}”? It will leave Active projects. Its identity, forms and authorization record will remain in Archived projects.`))return;
  setArchiving(item.id);setError(null);
  try{await supabaseProjectStateRepository.archiveProject(item.id);setItems(v=>v.filter(p=>p.id!==item.id))}
  catch(e){setError(e instanceof Error?e.message:'Project could not be archived.')}
  finally{setArchiving(null)}
 }
 return <section className="panel"><h2>{archived?'Archived projects':'Authorized projects'}</h2><p>Authorization records and published evidence stay attached to the same Project State. Archive old tests to remove them from the active list without deleting their history.</p><div className="form-actions" aria-label="Project list view"><button type="button" aria-pressed={!archived} disabled={Boolean(archiving)} onClick={()=>setArchived(false)}>Active projects</button><button type="button" aria-pressed={archived} disabled={Boolean(archiving)} onClick={()=>setArchived(true)}>Archived projects</button></div>{error?<p role="alert" className="error-message">{error}</p>:null}{loading?<p>Loading…</p>:items.length?<div className="opportunity-list">{items.map(item=><article className="opportunity-card" key={item.id}><strong>{item.name}</strong><span>{projectStageLabel(item.stage)}</span><p>{item.summary||'Authorized Ridgewood project.'}</p><AuthorizationRecord projectStateId={item.id}/>{!archived?<div className="form-actions"><button type="button" disabled={Boolean(archiving)} onClick={()=>void archive(item)}>{archiving===item.id?'Archiving…':'Archive project'}</button></div>:<small>Archived · historical record retained</small>}</article>)}</div>:<p>{archived?'No archived projects.':'No authorized projects yet.'}</p>}</section>;
}
