import { useRef, useState } from 'react';
import { scopeRepository, ScopeCommandError, type ScopeState, type ScopeQueryData, type ScopeQueryResponseInput } from '../../infrastructure/project-state/scopeRepository';
import { createRequestId } from '../../infrastructure/project-state/requestId';
import { PublishedDocumentView } from '../business/PublishedDocumentView';
import { useDrawerWorkState } from '../business/WorkspaceDrawer';

const blank = ():ScopeQueryData=>({scopeItemId:'',question:'',identifiedOn:'',ownerUserId:'',sourceRevisionId:'',partyIds:[]});
export function ScopeQueries({state,blocked,onRecorded,onWorkChange}:{state:ScopeState;blocked:boolean;onRecorded:(s:ScopeState)=>void;onWorkChange:(dirty:boolean,busy:boolean)=>void}){
 const [data,setData]=useState(blank),[queryId,setQueryId]=useState(''),[outcome,setOutcome]=useState<ScopeQueryResponseInput['outcome']|''>(''),[response,setResponse]=useState(''),[authorityId,setAuthorityId]=useState(''),[noImpact,setNoImpact]=useState(false);
 const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const pending=useRef<{kind:'capture';id:string;version:number;data:ScopeQueryData}|{kind:'respond';input:ScopeQueryResponseInput}|null>(null);
 useDrawerWorkState(dirty||Boolean(pending.current),busy);
 function changed(){setDirty(true);onWorkChange(true,false);setMessage('');}
 function patch(p:Partial<ScopeQueryData>){setData(d=>({...d,...p}));changed();}
 async function save(kind:'capture'|'respond'){
  if(busy||blocked)return;
  if(kind==='respond'&&!pending.current&&!window.confirm('Record this response? A clarification cannot change approved scope, cost, time or obligations. A potential change remains unauthorized.'))return;
  setBusy(true);onWorkChange(true,true);setError('');setMessage('');
  try{
   if(!pending.current){if(kind==='respond'&&!outcome)return;pending.current=kind==='capture'?{kind,id:createRequestId(),version:state.version,data:structuredClone(data)}:{kind,input:{id:createRequestId(),queryId,outcome:outcome as ScopeQueryResponseInput['outcome'],response,authorityId:outcome==='clarification'?authorityId:null,noImpact:outcome==='clarification'&&noImpact}};}
   const r=pending.current;
   const s=r.kind==='capture'?await scopeRepository.captureQuery(state.projectStateId,r.version,r.id,r.data):await scopeRepository.respondQuery(state.projectStateId,r.input);
   pending.current=null;setData(blank());setQueryId('');setOutcome('');setResponse('');setAuthorityId('');setNoImpact(false);setDirty(false);onWorkChange(false,false);onRecorded(s);
   setMessage(r.kind==='capture'?'Scope question saved. Readiness requires resolution.':r.input.outcome==='clarification'?'Clarification recorded. Approved scope remains unchanged.':'Potential change captured. Scope, cost and time approval remain outstanding.');
  }catch(e){
   if(e instanceof ScopeCommandError&&e.code==='P0001')pending.current=null;
   const messages:Record<string,string>={invalid_scope_query:'Complete the question, component, owner, source and date.',invalid_scope_query_date:'Enter a valid date identified, no later than today.',scope_version_conflict:'Scope changed. Reload before capturing the question.',scope_query_basis_changed:'The question refers to an earlier preparation. Refer any possible departure to Changes; it cannot be closed against a different version.',scope_query_already_responded:'A response is already recorded. Reload its history.',scope_strong_verification_required:'Recent strong verification is required to resolve a clarification.',scope_owner_authority_required:'Verified current owner authority is required.',scope_no_impact_confirmation_required:'Confirm that no approved scope, cost, time or obligation changes.',scope_source_not_current:'The source is no longer current. This response cannot close the question.',missing_scope_review_permission:'Scope review permission is required to close a clarification.'};
   setError(`${messages[e instanceof Error?e.message:'']??'The question or response could not be saved.'} ${pending.current?'Retry preserves the exact request.':'Your entries remain here.'}`);onWorkChange(true,false);
  }finally{setBusy(false);}
 }
 const locked=blocked||busy||!state.canEdit||Boolean(pending.current),required=<span className="setup-required">Required</span>;
 const capturing=Boolean(data.question||data.scopeItemId||data.ownerUserId||data.identifiedOn||data.sourceRevisionId||data.partyIds.length);
 const responding=Boolean(queryId||outcome||response||authorityId||noImpact);
 return <section className="setup-section scope-queries">
  <h4>5.3.4 Clarifications and potential changes</h4>
  <p>Record a question about a saved scope component. A response is not an instruction to change work. Questions and potential departures remain visible until governed resolution; the original baseline stays intact.</p>
  <details><summary>Capture a scope question</summary><fieldset disabled={locked||responding||state.version===0}>
   <label>Question component {required}<select value={data.scopeItemId} onChange={e=>patch({scopeItemId:e.target.value})}><option value="">Select from saved version {state.version}</option>{state.items.map(i=><option key={i.id} value={i.id}>{i.description||'Untitled scope component'}</option>)}</select></label>
   <label>Scope question {required}<textarea value={data.question} maxLength={4000} onChange={e=>patch({question:e.target.value})}/><small>Example: Does the finish schedule include the lobby threshold? State the uncertainty without directing changed work.</small></label>
   <label>Date identified {required}<input type="date" value={data.identifiedOn} onChange={e=>patch({identifiedOn:e.target.value})}/></label>
   <label>Question owner {required}<select value={data.ownerUserId} onChange={e=>patch({ownerUserId:e.target.value})}><option value="">Select an active workspace member</option>{state.queryOwners.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select><small>This assigns follow-up responsibility, not approval authority.</small></label>
   <label>Question source {required}<select value={data.sourceRevisionId} onChange={e=>patch({sourceRevisionId:e.target.value})}><option value="">Select a current published revision</option>{state.sources.filter(s=>s.state==='published').map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>
   <div className="contract-choices"><p>Affected parties <span className="optional-label">Optional if not yet known</span></p>{state.parties.filter(p=>!p.retired).map(p=><label key={p.id}><input type="checkbox" checked={data.partyIds.includes(p.id)} onChange={e=>patch({partyIds:e.target.checked?[...data.partyIds,p.id]:data.partyIds.filter(id=>id!==p.id)})}/><span>{p.label}</span></label>)}</div>
  </fieldset><button disabled={blocked||busy||!state.canEdit||responding||state.version===0} onClick={()=>void save('capture')}>{pending.current?.kind==='capture'?'Retry scope question':'Save scope question'}</button></details>
  <details><summary>Respond to a saved question</summary><fieldset disabled={locked||capturing}>
   <label>Open scope question {required}<select value={queryId} onChange={e=>{setQueryId(e.target.value);changed();}}><option value="">Select a question</option>{state.queries.filter(q=>!q.response).map(q=><option key={q.id} value={q.id}>Version {q.version} · {q.data.question}</option>)}</select></label>
   <label>Response disposition {required}<select value={outcome} onChange={e=>{setOutcome(e.target.value as typeof outcome);setAuthorityId('');setNoImpact(false);changed();}}><option value="">Select a disposition</option><option value="clarification">Clarification only — verified no change</option><option value="potential_change">Potential change — requires assessment and approval</option></select></label>
   <label>Scope response {required}<textarea value={response} maxLength={4000} onChange={e=>{setResponse(e.target.value);changed();}}/><small>Explain the source-based answer or describe what may change, known impacts and unresolved assumptions. Pricing and time remain unassessed in change intake.</small></label>
   {outcome==='clarification'&&<><label>Clarification authority {required}<select value={authorityId} onChange={e=>{setAuthorityId(e.target.value);changed();}}><option value="">Select verified owner evidence</option>{state.reviewAccess.ownerAuthorities.map(a=><option key={a.id} value={a.id}>{a.reference}</option>)}</select></label><div className="contract-choices"><label><input type="checkbox" checked={noImpact} onChange={e=>{setNoImpact(e.target.checked);changed();}}/><span>I verified this answer changes no approved scope, cost, time, quality, responsibility or obligation and waives no blocker. {required}</span></label></div><p>Scope review permission and recent strong verification are required. If impact is possible or unknown, refer a potential change.</p></>}
  </fieldset><button disabled={blocked||busy||!state.canEdit||capturing||!queryId||!outcome||!response.trim()} onClick={()=>void save('respond')}>{pending.current?.kind==='respond'?'Retry scope response':'Record scope response'}</button></details>
  {error&&<p role="alert">{error}</p>}<p role="status" aria-label="Scope question status">{message}</p>
  <ul aria-label="Scope question history">{state.queries.map(q=><li key={q.id}><strong>{q.data.question}</strong><p>Scope version {q.version} · Identified {q.data.identifiedOn} · {q.response?(q.response.outcome==='clarification'?'Clarification recorded':'Potential change — authorization outstanding'):'Open — resolution required'}</p><p>Owner: {state.queryOwners.find(o=>o.id===q.data.ownerUserId)?.label||q.data.ownerUserId}</p><p>Affected parties: {q.data.partyIds.map(id=>state.parties.find(p=>p.id===id)?.label||id).join(', ')||'Not yet supplied'}</p>{q.response&&<><p>{q.response.text}</p><p>Recorded {new Date(q.response.createdAt).toLocaleString()} · {q.response.actorUserId}</p>{q.response.authorityReference&&<p>Verified owner evidence: {q.response.authorityReference}</p>}{q.response.changeId&&<p>Change reference: {q.response.changeId}. Impact, commercial basis, time treatment, approval and implementation remain outstanding. No changed work is authorized.</p>}</>}<details><summary>Question and source record</summary><p>Question: {q.id}</p><p>{q.sourceSnapshot.title} · revision {q.sourceSnapshot.revisionNumber} · {q.sourceSnapshot.revisionId}</p><PublishedDocumentView revision={{documentId:q.sourceSnapshot.documentId,revisionId:q.sourceSnapshot.revisionId,revisionNumber:q.sourceSnapshot.revisionNumber,state:'published',title:q.sourceSnapshot.title,documentType:q.sourceSnapshot.documentType,category:q.sourceSnapshot.category,packageKey:'',data:q.sourceSnapshot.payload,snapshotAvailable:true,publishedAt:q.sourceSnapshot.publishedAt,publishedBy:q.sourceSnapshot.publishedBy,createdAt:'',changeNote:null,changes:[]}}/></details></li>)}</ul>
 </section>;
}
