-- Remove policy dependencies on the obsolete Opportunity entity.
drop policy if exists actions_select on public.actions; drop policy if exists actions_insert on public.actions; drop policy if exists actions_update on public.actions;
create policy actions_select on public.actions for select to authenticated using (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id)));
create policy actions_insert on public.actions for insert to authenticated with check (created_by=auth.uid() and exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id)));
create policy actions_update on public.actions for update to authenticated using (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))) with check (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id)));
drop policy if exists audit_workspace_select on public.audit_events; create policy audit_workspace_select on public.audit_events for select to authenticated using ((project_state_id is not null and exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))) or (project_id is not null and exists(select 1 from public.projects p where p.id=project_id and public.is_workspace_member(p.workspace_id))));
drop policy if exists authorization_records_workspace_select on public.authorization_records; create policy authorization_records_workspace_select on public.authorization_records for select to authenticated using (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id)));
drop policy if exists decisions_select on public.decisions; drop policy if exists decisions_insert on public.decisions; create policy decisions_select on public.decisions for select to authenticated using (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))); create policy decisions_insert on public.decisions for insert to authenticated with check (actor_user_id=auth.uid() and exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id)));
drop policy if exists evidence_select on public.evidence_references; drop policy if exists evidence_insert on public.evidence_references; drop policy if exists evidence_update on public.evidence_references; create policy evidence_select on public.evidence_references for select to authenticated using (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))); create policy evidence_insert on public.evidence_references for insert to authenticated with check (created_by=auth.uid() and exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))); create policy evidence_update on public.evidence_references for update to authenticated using (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))) with check (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id)));
drop policy if exists risks_select on public.risk_issues; drop policy if exists risks_insert on public.risk_issues; drop policy if exists risks_update on public.risk_issues; create policy risks_select on public.risk_issues for select to authenticated using (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))); create policy risks_insert on public.risk_issues for insert to authenticated with check (created_by=auth.uid() and exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))); create policy risks_update on public.risk_issues for update to authenticated using (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id))) with check (exists(select 1 from public.project_states ps where ps.id=project_state_id and public.is_workspace_member(ps.workspace_id)));
