alter table public.actions add column if not exists lifecycle_stage text, add column if not exists capability_key text;
alter table public.risk_issues add column if not exists lifecycle_stage text, add column if not exists capability_key text;
alter table public.decisions add column if not exists lifecycle_stage text, add column if not exists capability_key text;
alter table public.evidence_references add column if not exists lifecycle_stage text, add column if not exists capability_key text;

alter table public.actions add constraint actions_lifecycle_stage_check check (lifecycle_stage is null or lifecycle_stage in ('opportunity','qualification','predevelopment','authorization')) not valid;
alter table public.risk_issues add constraint risk_issues_lifecycle_stage_check check (lifecycle_stage is null or lifecycle_stage in ('opportunity','qualification','predevelopment','authorization')) not valid;
alter table public.decisions add constraint decisions_lifecycle_stage_check check (lifecycle_stage is null or lifecycle_stage in ('opportunity','qualification','predevelopment','authorization')) not valid;
alter table public.evidence_references add constraint evidence_references_lifecycle_stage_check check (lifecycle_stage is null or lifecycle_stage in ('opportunity','qualification','predevelopment','authorization')) not valid;

create index if not exists actions_project_state_context_idx on public.actions(project_state_id,lifecycle_stage,capability_key);
create index if not exists risk_issues_project_state_context_idx on public.risk_issues(project_state_id,lifecycle_stage,capability_key);
create index if not exists decisions_project_state_context_idx on public.decisions(project_state_id,lifecycle_stage,capability_key);
create index if not exists evidence_references_project_state_context_idx on public.evidence_references(project_state_id,lifecycle_stage,capability_key);

create or replace function public.create_project_state_action_command(project_state_input uuid,title_input text,due_date_input date default null,lifecycle_stage_input text default null,capability_key_input text default null) returns void language plpgsql security definer set search_path=public as $$ declare actor uuid:=auth.uid(); begin if actor is null then raise exception 'authentication_required'; end if; if nullif(btrim(title_input),'') is null then raise exception 'action_title_required'; end if; if lifecycle_stage_input is not null and lifecycle_stage_input not in ('opportunity','qualification','predevelopment','authorization') then raise exception 'invalid_lifecycle_stage'; end if; insert into public.actions(project_state_id,title,due_date,status,created_by,lifecycle_stage,capability_key) values(project_state_input,btrim(title_input),due_date_input,'open',actor,lifecycle_stage_input,nullif(btrim(capability_key_input),'')); end $$;
create or replace function public.create_project_state_risk_issue_command(project_state_input uuid,kind_input text,title_input text,severity_input text default null,lifecycle_stage_input text default null,capability_key_input text default null) returns void language plpgsql security definer set search_path=public as $$ declare actor uuid:=auth.uid(); begin if actor is null then raise exception 'authentication_required'; end if; if nullif(btrim(title_input),'') is null then raise exception 'risk_issue_title_required'; end if; if lifecycle_stage_input is not null and lifecycle_stage_input not in ('opportunity','qualification','predevelopment','authorization') then raise exception 'invalid_lifecycle_stage'; end if; insert into public.risk_issues(project_state_id,kind,title,severity,status,created_by,lifecycle_stage,capability_key) values(project_state_input,coalesce(nullif(btrim(kind_input),''),'risk'),btrim(title_input),nullif(btrim(severity_input),''),'open',actor,lifecycle_stage_input,nullif(btrim(capability_key_input),'')); end $$;
create or replace function public.record_project_state_decision_command(project_state_input uuid,decision_type_input text,outcome_input text,rationale_input text default null,authority_basis_input text default null,lifecycle_stage_input text default null,capability_key_input text default null) returns void language plpgsql security definer set search_path=public as $$ declare actor uuid:=auth.uid(); begin if actor is null then raise exception 'authentication_required'; end if; if nullif(btrim(decision_type_input),'') is null or nullif(btrim(outcome_input),'') is null then raise exception 'decision_type_and_outcome_required'; end if; if lifecycle_stage_input is not null and lifecycle_stage_input not in ('opportunity','qualification','predevelopment','authorization') then raise exception 'invalid_lifecycle_stage'; end if; insert into public.decisions(project_state_id,decision_type,outcome,rationale,authority_basis,actor_user_id,lifecycle_stage,capability_key) values(project_state_input,btrim(decision_type_input),btrim(outcome_input),nullif(btrim(rationale_input),''),nullif(btrim(authority_basis_input),''),actor,lifecycle_stage_input,nullif(btrim(capability_key_input),'')); end $$;
create or replace function public.create_project_state_evidence_command(project_state_input uuid,title_input text,source_system_input text,source_url_input text,provenance_note_input text,knowledge_state_input public.knowledge_state,lifecycle_stage_input text default null,capability_key_input text default null) returns void language plpgsql security definer set search_path=public as $$ declare actor uuid:=auth.uid(); begin if actor is null then raise exception 'authentication_required'; end if; if nullif(btrim(title_input),'') is null then raise exception 'evidence_title_required'; end if; if lifecycle_stage_input is not null and lifecycle_stage_input not in ('opportunity','qualification','predevelopment','authorization') then raise exception 'invalid_lifecycle_stage'; end if; insert into public.evidence_references(project_state_id,title,source_system,source_url,provenance_note,knowledge_state,created_by,lifecycle_stage,capability_key) values(project_state_input,btrim(title_input),coalesce(nullif(btrim(source_system_input),''),'google_drive'),nullif(btrim(source_url_input),''),nullif(btrim(provenance_note_input),''),knowledge_state_input,actor,lifecycle_stage_input,nullif(btrim(capability_key_input),'')); end $$;

grant execute on function public.create_project_state_action_command(uuid,text,date,text,text) to authenticated;
grant execute on function public.create_project_state_risk_issue_command(uuid,text,text,text,text,text) to authenticated;
grant execute on function public.record_project_state_decision_command(uuid,text,text,text,text,text,text) to authenticated;
grant execute on function public.create_project_state_evidence_command(uuid,text,text,text,text,public.knowledge_state,text,text) to authenticated;
