alter table public.opportunity_qualification_findings add column if not exists project_state_id uuid references public.project_states(id) on delete cascade; alter table public.opportunity_qualification_decisions add column if not exists project_state_id uuid references public.project_states(id) on delete cascade; alter table public.predevelopment_domains add column if not exists project_state_id uuid references public.project_states(id) on delete cascade;
update public.opportunity_qualification_findings f set project_state_id=o.project_state_id from public.opportunities o where f.opportunity_id=o.id and f.project_state_id is null;
update public.opportunity_qualification_decisions d set project_state_id=o.project_state_id from public.opportunities o where d.opportunity_id=o.id and d.project_state_id is null;
update public.predevelopment_domains p set project_state_id=o.project_state_id from public.opportunities o where p.opportunity_id=o.id and p.project_state_id is null;
alter table public.opportunity_qualification_findings alter column project_state_id set not null; alter table public.opportunity_qualification_decisions alter column project_state_id set not null; alter table public.predevelopment_domains alter column project_state_id set not null;
alter table public.opportunity_qualification_findings drop constraint if exists opportunity_qualification_findings_opportunity_id_area_key; alter table public.predevelopment_domains drop constraint if exists predevelopment_domains_opportunity_id_domain_key_key;
alter table public.opportunity_qualification_findings add constraint opportunity_qualification_findings_project_state_area_key unique(project_state_id,area); alter table public.predevelopment_domains add constraint predevelopment_domains_project_state_domain_key_key unique(project_state_id,domain_key);
create index if not exists qualification_decisions_project_state_idx on public.opportunity_qualification_decisions(project_state_id,decided_at desc);
comment on column public.opportunity_qualification_findings.project_state_id is 'Canonical parent. Qualification is a stage of Project State.'; comment on column public.opportunity_qualification_decisions.project_state_id is 'Canonical parent. Qualification decisions govern Project State stage progression.'; comment on column public.predevelopment_domains.project_state_id is 'Canonical parent. Predevelopment is a stage of Project State.';
