import { supabase } from '../auth/supabaseClient';
import type { ChangeData, ChangeState } from './changeRepository';
import type { ScopeState, ScopeOutcome } from './scopeRepository';
export interface ProposalData {recipientPartyId:string;clientAmount:string;feeTreatment:string;commercialTerms:string;proposalRevisionId:string;validUntil:string}
export const blankProposal=():ProposalData=>({recipientPartyId:'',clientAmount:'',feeTreatment:'',commercialTerms:'',proposalRevisionId:'',validUntil:''});
export interface ProposalSource {recipient?:{id:string;label:string}|null;documentId:string;revisionId:string;title:string;revisionNumber:number;documentType:string;category:string;publishedAt:string;publishedBy:string;payload:Record<string,unknown>}
export interface ProposalDecision {id:string;version:number;sequence:number;authorityId:string;outcome:ScopeOutcome;rationale:string;confirmed:boolean}
export interface ProposalState {projectStateId:string;changeId:string;assessment:ChangeState;basis:ChangeData|null;basisVersion:number;version:number;data:ProposalData|null;sourceSnapshot:ProposalSource|null;blockers:string[];sequence:number;releaseAuthorized:boolean;clientAccepted:false;workAuthorized:false;canEdit:boolean;reviewAccess:ScopeState['reviewAccess'];parties:ScopeState['parties'];history:{version:number;assessmentVersion:number;basis:ChangeData;data:ProposalData;sourceSnapshot:ProposalSource;createdAt:string;actorUserId:string}[];decisions:{id:string;version:number;sequence:number;outcome:ScopeOutcome;rationale:string;authorityReference:string;createdAt:string;actorUserId:string}[];savedVersion?:number}
export class ProposalCommandError extends Error {constructor(message:string,public code:string){super(message);}}
async function call(name:string,args:Record<string,unknown>):Promise<ProposalState>{const {data,error}=await supabase.rpc(name,args);if(error)throw new ProposalCommandError(error.message,error.code);return data;}
const ids=(p:string,c:string)=>({project_state_input:p,change_id_input:c});
export const proposalRepository={read:(p:string,c:string)=>call('read_change_proposal',ids(p,c)),save:(p:string,c:string,a:number,v:number,id:string,data:ProposalData)=>call('save_change_proposal',{...ids(p,c),assessment_version_input:a,expected_version_input:v,request_id_input:id,data_input:data}),decide:(p:string,c:string,d:ProposalDecision)=>call('decide_change_proposal',{...ids(p,c),version_input:d.version,sequence_input:d.sequence,request_id_input:d.id,authority_id_input:d.authorityId,outcome_input:d.outcome,rationale_input:d.rationale,confirmed_input:d.confirmed})};
