import type { CommercialStage, ProjectPriority, ProjectStage, ProjectState, ProjectStateStatus } from '../../domain/project-state/projectState';
import { supabase } from '../auth/supabaseClient';

export type StageRequirementStatus = 'not_started' | 'in_progress' | 'satisfied' | 'blocked' | 'unknown' | 'not_applicable';
export interface ProjectStateStageRequirement { requirementKey: string; label: string; status: StageRequirementStatus; required: boolean; notes?: string; stage?: ProjectStage; gateKey?: string }
export interface OpportunityBasicsInput { name: string; organizationId?:string; location?: string; sector?: string; source?: string; summary?: string; nextAction?: string; priority?:ProjectPriority; probability?:number; ownerUserId?:string }
export interface WorkspaceMemberOption { userId:string; label:string }
export interface OrganizationOption { id:string; name:string; organizationType?:string }
export interface StageRequirementInput { stage: ProjectStage; requirementKey: string; label: string; status: StageRequirementStatus; required?: boolean; notes?: string; gateKey?: string }
export interface AuthorizationPackageSummary { openDrafts:number; publishedDocuments:number; evidence:number; decisions:number; unresolvedEvidence:number; unresolvedRequired:number; readiness:[string,StageRequirementStatus][] }
export interface AuthorizationRecordSummary { id:string; outcome:string; authorityBasis?:string; createdAt:string; actorUserId:string; readinessSnapshot:unknown; evidenceSnapshot:unknown }
export interface AuthorizationAmendmentSummary { id:string; authorizationRecordId:string; amendmentType:'correction'|'addendum'; summary:string; rationale:string; authorityBasis?:string; documentRecordId?:string; originalRevisionId?:string; changedFields?:Record<string,unknown>; actorUserId:string; createdAt:string }
export interface DispositionEvent { id:string; eventType:string; priorStatus?:string; newStatus?:string; priorStage:string; reason?:string; basis?:string; actorUserId:string; createdAt:string }
export type BusinessDispositionView='pipeline'|'held'|'inactive';

type ProjectStateRow = {id:string;name:string;stage:ProjectStage|null;status:ProjectStateStatus|null;commercial_stage:CommercialStage|null;commercial_probability:number|null;priority:ProjectPriority|null;owner_user_id:string|null;organization_id:string|null;site_location:string|null;sector:string|null;source_context:string|null;summary:string|null;next_action:string|null;created_at:string;updated_at:string};
type RequirementRow = { stage?: ProjectStage; gate_key?: string | null; requirement_key: string; label: string; status: StageRequirementStatus; required: boolean; notes: string | null };
type DispositionEventRow={id:string;event_type:string;prior_status:string|null;new_status:string|null;prior_stage:string;reason:string|null;basis:string|null;actor_user_id:string;created_at:string};
type AuthorizationAmendmentRow={id:string;authorization_record_id:string;amendment_type:'correction'|'addendum';summary:string;rationale:string;authority_basis:string|null;document_record_id:string|null;original_revision_id:string|null;changed_fields:Record<string,unknown>|null;actor_user_id:string;created_at:string};
function fromRow(row:ProjectStateRow):ProjectState{return{id:row.id,name:row.name,stage:row.stage??'opportunity',status:row.status??'active',commercialStage:row.commercial_stage??'opportunity',probability:row.commercial_probability??undefined,priority:row.priority??'medium',ownerPersonId:row.owner_user_id??undefined,organizationId:row.organization_id??undefined,location:row.site_location??undefined,sector:row.sector??undefined,source:row.source_context??undefined,summary:row.summary??undefined,nextAction:row.next_action??undefined,createdAt:row.created_at,updatedAt:row.updated_at}}
function requirementFromRow(row:RequirementRow):ProjectStateStageRequirement{return{requirementKey:row.requirement_key,label:row.label,status:row.status,required:row.required,notes:row.notes??undefined,stage:row.stage,gateKey:row.gate_key??undefined}}
function dispositionEventFromRow(row:DispositionEventRow):DispositionEvent{return{id:row.id,eventType:row.event_type,priorStatus:row.prior_status??undefined,newStatus:row.new_status??undefined,priorStage:row.prior_stage,reason:row.reason??undefined,basis:row.basis??undefined,actorUserId:row.actor_user_id,createdAt:row.created_at}}
function amendmentFromRow(row:AuthorizationAmendmentRow):AuthorizationAmendmentSummary{return{id:row.id,authorizationRecordId:row.authorization_record_id,amendmentType:row.amendment_type,summary:row.summary,rationale:row.rationale,authorityBasis:row.authority_basis??undefined,documentRecordId:row.document_record_id??undefined,originalRevisionId:row.original_revision_id??undefined,changedFields:row.changed_fields??undefined,actorUserId:row.actor_user_id,createdAt:row.created_at}}
async function context(){const{data:authData,error:authError}=await supabase.auth.getUser();if(authError||!authData.user)throw authError??new Error('Authentication required.');const{data:membership,error:membershipError}=await supabase.from('workspace_memberships').select('workspace_id').eq('user_id',authData.user.id).eq('status','active').limit(1).single();if(membershipError||!membership)throw membershipError??new Error('No active Ridgewood workspace is available for this account.');return{userId:authData.user.id,workspaceId:membership.workspace_id as string}}
async function authorizationError(error:unknown):Promise<Error>{if(error&&typeof error==='object'&&'context'in error){const response=(error as{context?:unknown}).context;if(response instanceof Response){try{const payload=await response.clone().json() as{message?:unknown;error?:unknown;code?:unknown};const message=typeof payload.message==='string'&&payload.message.trim()?payload.message.trim():typeof payload.error==='string'&&payload.error.trim()?payload.error.trim().replaceAll('_',' '):'';const code=typeof payload.code==='string'&&payload.code.trim()?` (${payload.code.trim()})`:'';if(message)return new Error(`Project Authorization failed: ${message}${code}`)}catch{try{const text=(await response.clone().text()).trim();if(text)return new Error(`Project Authorization failed: ${text.slice(0,300)}`)}catch{/* fall through */}}}}if(error instanceof Error&&error.message)return new Error(`Project Authorization failed: ${error.message}`);return new Error('Project Authorization failed for an unknown reason. Reload this Project State before retrying.')}
const authorizedStages:ProjectStage[]=['project_authorization_setup','preconstruction_mobilization','construction_control','completion_turnover','project_closeout','warranty_final_close','closed'];
export const supabaseProjectStateRepository={
 async listPortfolio():Promise<ProjectState[]>{const{workspaceId}=await context();const items:ProjectState[]=[];for(let page=0;;page+=1000){const{data,error}=await supabase.from('project_states').select('*').eq('workspace_id',workspaceId).is('archived_at',null).order('id').range(page,page+999);if(error)throw error;items.push(...((data??[])as ProjectStateRow[]).map(fromRow));if((data?.length??0)<1000)break;}return items},
 async list(view:BusinessDispositionView='pipeline'):Promise<ProjectState[]>{const{workspaceId}=await context();let q=supabase.from('project_states').select('*').eq('workspace_id',workspaceId).is('archived_at',null).not('stage','in',`(${authorizedStages.join(',')})`);q=view==='pipeline'?q.eq('status','active'):view==='held'?q.eq('status','held'):q.in('status',['declined','withdrawn_lost','lost']);const{data,error}=await q.order('updated_at',{ascending:false});if(error)throw error;return((data??[])as ProjectStateRow[]).map(fromRow)},
 async listArchivedPreauthorization():Promise<ProjectState[]>{const{workspaceId}=await context();const{data,error}=await supabase.from('project_states').select('*').eq('workspace_id',workspaceId).not('archived_at','is',null).not('stage','in',`(${authorizedStages.join(',')})`).order('updated_at',{ascending:false});if(error)throw error;return((data??[])as ProjectStateRow[]).map(fromRow)},
 async get(id:string):Promise<ProjectState>{const{workspaceId}=await context();const{data,error}=await supabase.from('project_states').select('*').eq('workspace_id',workspaceId).eq('id',id).is('archived_at',null).single();if(error)throw error;return fromRow(data as ProjectStateRow)},
 async workspaceMembers():Promise<WorkspaceMemberOption[]>{const{workspaceId}=await context();const{data,error}=await supabase.from('workspace_memberships').select('user_id').eq('workspace_id',workspaceId).eq('status','active').order('created_at');if(error)throw error;return(data??[]).map(v=>({userId:v.user_id as string,label:(v.user_id as string).slice(0,8)}))},
 async organizations():Promise<OrganizationOption[]>{const{workspaceId}=await context();const{data,error}=await supabase.from('organizations').select('id,name,organization_type').eq('workspace_id',workspaceId).order('name');if(error)throw error;return(data??[]).map(v=>({id:v.id as string,name:v.name as string,organizationType:(v.organization_type as string|null)??undefined}))},
 async createOrganization(name:string,organizationType='client'):Promise<OrganizationOption>{const{userId,workspaceId}=await context();const trimmed=name.trim();if(!trimmed)throw new Error('Organization name is required.');const{data,error}=await supabase.from('organizations').insert({workspace_id:workspaceId,name:trimmed,organization_type:organizationType,created_by:userId}).select('id,name,organization_type').single();if(error)throw error;return{id:data.id as string,name:data.name as string,organizationType:(data.organization_type as string|null)??undefined}},
 async dispositionHistory(id:string):Promise<DispositionEvent[]>{const{workspaceId}=await context();const{data,error}=await supabase.from('project_state_disposition_events').select('id,event_type,prior_status,new_status,prior_stage,reason,basis,actor_user_id,created_at').eq('workspace_id',workspaceId).eq('project_state_id',id).order('created_at',{ascending:false});if(error)throw error;return((data??[])as DispositionEventRow[]).map(dispositionEventFromRow)},
 async reassessmentRequirements(id:string):Promise<ProjectStateStageRequirement[]>{await context();const{data,error}=await supabase.from('project_state_stage_requirements').select('stage,gate_key,requirement_key,label,status,required,notes').eq('project_state_id',id).eq('requirement_key','restoration_reassessment').order('updated_at',{ascending:false});if(error)throw error;return((data??[])as RequirementRow[]).map(requirementFromRow)},
 async listProjects(archived=false):Promise<ProjectState[]>{const{workspaceId}=await context();let query=supabase.from('project_states').select('*').eq('workspace_id',workspaceId).in('stage',authorizedStages);query=archived?query.not('archived_at','is',null):query.is('archived_at',null);const{data,error}=await query.order('updated_at',{ascending:false});if(error)throw error;return((data??[])as ProjectStateRow[]).map(fromRow)},
 async authorizationRecord(id:string):Promise<AuthorizationRecordSummary|null>{await context();const{data,error}=await supabase.from('authorization_records').select('id,outcome,authority_basis,readiness_snapshot,evidence_snapshot,actor_user_id,created_at').eq('project_state_id',id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(!data)return null;return{id:data.id as string,outcome:data.outcome as string,authorityBasis:(data.authority_basis as string|null)??undefined,readinessSnapshot:data.readiness_snapshot,evidenceSnapshot:data.evidence_snapshot,actorUserId:data.actor_user_id as string,createdAt:data.created_at as string}},
 async authorizationAmendments(id:string):Promise<AuthorizationAmendmentSummary[]>{await context();const{data,error}=await supabase.from('authorization_amendments').select('id,authorization_record_id,amendment_type,summary,rationale,authority_basis,document_record_id,original_revision_id,changed_fields,actor_user_id,created_at').eq('project_state_id',id).order('created_at',{ascending:false});if(error)throw error;return((data??[])as AuthorizationAmendmentRow[]).map(amendmentFromRow)},
 async recordAuthorizationAmendment(id:string,amendmentType:'correction'|'addendum',summary:string,rationale:string,authorityBasis?:string,documentRecordId?:string,originalRevisionId?:string,changedFields?:Record<string,unknown>):Promise<AuthorizationAmendmentSummary>{await context();const{data,error}=await supabase.rpc('record_authorization_amendment',{project_state_input:id,amendment_type_input:amendmentType,summary_input:summary,rationale_input:rationale,authority_basis_input:authorityBasis??null,evidence_input:[],document_record_input:documentRecordId??null,original_revision_input:originalRevisionId??null,changed_fields_input:changedFields??null});if(error)throw error;return amendmentFromRow(data as AuthorizationAmendmentRow)},
 async create(input:Omit<ProjectState,'id'|'stage'|'status'|'createdAt'|'updatedAt'>):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('create_project_state',{project_state_input:{name:input.name,commercial_stage:input.commercialStage,commercial_probability:input.probability??null,priority:input.priority,organization_id:input.organizationId??null,site_location:input.location??null,sector:input.sector??null,source_context:input.source??null,summary:input.summary??null,next_action:input.nextAction??null}});if(error)throw error;return fromRow(data as ProjectStateRow)},
 async updateOpportunityBasics(id:string,input:OpportunityBasicsInput):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('update_project_state_opportunity_basics',{project_state_input:id,basics_input:{name:input.name,...(input.organizationId!==undefined?{organization_id:input.organizationId||null}:{}),site_location:input.location??null,sector:input.sector??null,source_context:input.source??null,summary:input.summary??null,...(input.nextAction!==undefined?{next_action:input.nextAction||null}:{}),...(input.priority!==undefined?{priority:input.priority}:{}),...(input.probability!==undefined?{commercial_probability:input.probability}:{}),...(input.ownerUserId!==undefined?{owner_user_id:input.ownerUserId||null}:{})}});if(error)throw error;return fromRow(data as ProjectStateRow)},
 async opportunityRequirements(id:string):Promise<ProjectStateStageRequirement[]>{await context();const{data,error}=await supabase.rpc('refresh_project_state_opportunity_requirements',{project_state_input:id});if(error)throw error;return((data??[])as RequirementRow[]).map(requirementFromRow)},
 async stageRequirements(id:string,stage?:ProjectStage):Promise<ProjectStateStageRequirement[]>{await context();const{data,error}=await supabase.rpc('list_project_state_stage_requirements',{project_state_input:id,stage_input:stage??null});if(error)throw error;return((data??[])as RequirementRow[]).map(requirementFromRow)},
 async authorizationPackage(id:string):Promise<AuthorizationPackageSummary>{await context();const[domains,drafts,published,evidence,decisions,requirements]=await Promise.all([supabase.from('predevelopment_domains').select('domain_key,readiness').eq('project_state_id',id),supabase.from('document_records').select('id,document_revisions!inner(id)').eq('project_state_id',id).eq('document_revisions.state','draft').is('document_revisions.archived_at',null),supabase.from('document_records').select('id,document_revisions!inner(id)').eq('project_state_id',id).eq('document_revisions.state','published').is('document_revisions.archived_at',null),supabase.from('evidence_references').select('id,knowledge_state').eq('project_state_id',id),supabase.from('decisions').select('id').eq('project_state_id',id),supabase.from('project_state_stage_requirements').select('status,required').eq('project_state_id',id).eq('stage','authorization')]);for(const r of[domains,drafts,published,evidence,decisions,requirements])if(r.error)throw r.error;const ev=evidence.data??[],req=requirements.data??[];return{openDrafts:(drafts.data??[]).length,publishedDocuments:(published.data??[]).length,evidence:ev.length,decisions:(decisions.data??[]).length,unresolvedEvidence:ev.filter(v=>v.knowledge_state==='unknown'||v.knowledge_state==='unverified').length,unresolvedRequired:req.filter(v=>v.required&&!['satisfied','not_applicable'].includes(v.status)).length,readiness:(domains.data??[]).map(v=>[v.domain_key,v.readiness as StageRequirementStatus])}},
 async ensureProjectAuthorizationSetupRequirements(id:string):Promise<ProjectStateStageRequirement[]>{await context();const{data,error}=await supabase.rpc('ensure_project_authorization_setup_requirements',{project_state_input:id});if(error)throw error;return((data??[])as RequirementRow[]).map(requirementFromRow)},
 async setStageRequirement(id:string,input:StageRequirementInput):Promise<ProjectStateStageRequirement>{await context();const{data,error}=await supabase.rpc('set_project_state_stage_requirement',{project_state_input:id,stage_input:input.stage,requirement_key_input:input.requirementKey,label_input:input.label,status_input:input.status,required_input:input.required??true,notes_input:input.notes??null,gate_key_input:input.gateKey??null});if(error)throw error;return requirementFromRow(data as RequirementRow)},
 async setDisposition(id:string,disposition:'hold'|'resume'|'decline'|'withdraw_lost',reason:string,basis?:string):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('set_project_state_preauthorization_disposition',{project_state_input:id,disposition_input:disposition,reason_input:reason,basis_input:basis??null});if(error)throw error;return fromRow(data as ProjectStateRow)},
 async archiveProject(id:string):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('archive_project_state',{project_state_input:id});if(error)throw error;return fromRow(data as ProjectStateRow)},
 async archivePreauthorization(id:string,reason:string,basis?:string):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('archive_preauthorization_project_state',{project_state_input:id,reason_input:reason,basis_input:basis??null});if(error)throw error;return fromRow(data as ProjectStateRow)},
 async restore(id:string,reason:string,basis?:string):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('restore_preauthorization_project_state',{project_state_input:id,reason_input:reason,basis_input:basis??null});if(error)throw error;return fromRow(data as ProjectStateRow)},
 async advanceToQualification(id:string):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('advance_project_state_to_qualification',{project_state_input:id});if(error)throw error;return fromRow(data as ProjectStateRow)},async resumeHeld(id:string,reason:string):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('set_project_state_preauthorization_disposition',{project_state_input:id,disposition_input:'resume',reason_input:reason,basis_input:null});if(error)throw error;return fromRow(data as ProjectStateRow)},async enterAuthorization(id:string):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('enter_project_state_authorization',{project_state_input:id});if(error)throw error;return fromRow(data as ProjectStateRow)},async authorize(id:string,authorityBasis?:string):Promise<ProjectState>{await context();const{data,error}=await supabase.functions.invoke('project-authorization',{body:{projectStateId:id,authorityBasis:authorityBasis??''}});if(error)throw await authorizationError(error);if(!data||typeof data!=='object'||!('projectState'in data))throw new Error('Project Authorization failed: the server did not return the updated Project State.');return fromRow((data as{projectState:ProjectStateRow}).projectState)},async enterPreconstructionMobilization(id:string):Promise<ProjectState>{await context();const{data,error}=await supabase.rpc('enter_project_state_preconstruction_mobilization',{project_state_input:id});if(error)throw error;return fromRow(data as ProjectStateRow)}
};